### ISSUE TITLE
El Capitan: Files Created which cannot be deleted

### ISSUE THREAD

**Issue by bennyp123** [ImageOptim/ImageOptim#115]
When dragging files form desktop to IO, New PNG files are created on the desktop which cannot be deleted. These files don't appear in directory listing in terminal.

**Comment by pornel** [comment]
This looks like a Finder bug. There should be no way to create an undeletable phantom file that is only visible in Finder.

Can you file a bug at https://bugreport.apple.com?

**Comment by nicholaelaw** [comment]
Are you sure it's specific to IO? I've encountered similar problems in Yosemite, particularly with some problematic Chrome downloaded files. I cannot delete the file, nor open it. A reboot usually fixes this.

Oh and I concur that this is a Finder bug, or some hiccup in the file system. I've not yet encountered this problem in El Capitan with either IO or Chrome.

**Comment by waldoj** [comment]
FWIW, this happens every single time I optimize an image an ImageOptim 5–10 times each day. (I'm a bit of a fanatic about image optimization, and a shameless ImageOptim promoter, as a result.)  After enough of them build up on my desktop, I restart the Finder to make them go away. I have not seen this happen with any other program.

Specifically, the error message is:

> The item "image.png" can't be moved to the Trash because it can't be deleted.

The file does not appear when listing files in the terminal.

I appreciate that this could _only_ be a Finder bug, but perhaps there's a way to refactor the process of overwriting the existing file that might work around this problem? @pornel, are you able to reproduce this bug?

**Comment by pornel** [comment]
I can't reproduce this problem.

You can change how saving is done in Preferences with the "Preserve file permissions…" option.

**Comment by waldoj** [comment]
> You can change how saving is done in Preferences with the "Preserve file permissions…" option.

Ah-ha! That fixed it. @bennyp123, does that resolve the problem for you?

**Comment by bennyp123** [comment]
Today I disabled "preserve file permissions" and then optimised a 5k screen grab of Star Trek The Next Generation (pfft, as if it needed optimisation :)) from the desktop. It's a huge file so I actually had to stop optimisation, but after that, and with a few other test files, there were no ghost icons.

So yes it looks like disabling preserve file permissions solves the problem.

**Comment by pornel** [comment]
I haven't seen the bug in a while, so hopefully Apple has fixed it
