### ISSUE TITLE
Add option to reduce number of active threads

### ISSUE THREAD

**Issue by RJWoodhead** [ImageOptim/ImageOptim#118]
ImageOptim appears to check to see how many cores the machine has and spawns threads accordingly. But sometimes you don't want the app to peg the needle at 100% CPU, and it can certainly slow other apps to a crawl. A way to tell the app to spawn fewer threads and/or reduce their priority might make it a better neighbor.

**Comment by fulldecent** [comment]
FYI, the workaround today is to run this from the command line: 

    renice 20 $(pgrep ImageOptim)

I would vote against this feature. Max threads is good. It is probably a good default for this to run at +15 all the time because it is a non-interactive batch process. This better default would probably fix everyone's problem.

I have asked SO here https://stackoverflow.com/questions/33884553/mac-os-x-documentation-of-recommended-nice-levels if there is a better choice than +15.

**Comment by RJWoodhead** [comment]
It occurs to me that you don't want to renice the main UI thread; it is the various worker threads (Zopfli, PNGOUT, etc.) that get spawned that should be reniced. Perhaps a niceness slider that lets you set them from 0 to 20 would be a decent (and simple) solution.

**Comment by pornel** [comment]
ImageOptim already does `renice 10` on all tools launched:

https://github.com/pornel/ImageOptim/blob/231cccea81573bccfb4afb01f141b02cf7e7aa0d/imageoptim/Workers/CommandWorker.m#L87

**Comment by RJWoodhead** [comment]
I did some informal tests. Renicing to 20 does not appear to significantly change how friendly ImageOptim is to other apps -- and the nice-20 threads seem to get about as much CPU as the nice-10 ones. My guess is the reason is that since there is a worker thread on each core, the caches start thrashing.

It might be worth doing some testing running fewer threads than cores. Depending on how smart the process scheduler is, you might end up getting similar or better performance if the non ImageOptim threads tend to stay on the extra cores.

I don't develop in Xcode, but if someone wants to hack together a quick test version that lets me change the number of cores & nice level (say by changing a .plist), and reports elapsed time, then I'd be happy to run some tests.

**Comment by pornel** [comment]
You can change number of threads with

```sh
defaults write net.pornel.imageoptim RunConcurrentFiles 1
defaults write net.pornel.imageoptim RunConcurrentDirscans 1
```

**Comment by pornel** [comment]
Note that optimization is very CPU bound and running on 3 of 4 cores will reduce performance by 25% (although the calculation isn't as straightforward with virtual hyperthreading cores).

**Comment by RJWoodhead** [comment]
I did a quick check and setting RunConcurrentFiles to 1 does not affect the number of worker threads launched, or the number of files showing as being concurrently processed.

I did a quick grep of the source and it appears that these values are being overwritten in ImageOptimController.m applicationWillFinishLaunching

    defs[@"RunConcurrentFiles"] = @(maxTasks);
    defs[@"RunConcurrentDirscans"] = @((int)ceil((double)maxTasks/3.9));

I'm guess you only really want to do that if the key doesn't exist in the dictionary.

**Comment by pornel** [comment]
Note that this dictionary is used for the "defaults of defaults": 

```objc
    NSUserDefaults *userDefaults = [NSUserDefaults standardUserDefaults];
    [userDefaults registerDefaults:defs];
```

so user's preference takes precedence.

**Comment by RJWoodhead** [comment]
Well, if you set RunConcurrentFiles to 1, the behavior of the app is unchanged. It processes multiple files at once, and launches one worker thread for each core.

**Comment by pornel** [comment]
I've verified that it works as intended. `defaults write net.pornel.imageoptim RunConcurrentFiles 1` set before the app starts configures it to use 1 thread for cpu-intensive optimizations.

**Comment by RJWoodhead** [comment]
Hmmm... maybe I'm doing something wrong, but I've confirmed that RunConcurrentFiles is 1 in the defaults, relaunched the app, and it's still processing multiple files. Same behavior in the latest beta. Here's a screenshot...

![imageoptim-ss](https://cloud.githubusercontent.com/assets/10821401/11423354/8b42358e-9411-11e5-99ff-e61ad0eaba0e.png)

**Comment by fulldecent** [comment]
FYI, more discussion on priority here:
https://stackoverflow.com/questions/33884553/correct-nice-posix-scheduling-priority-for-batch-processing-program/34198750#34198750

I am not sure if this is helpful or redundant, just providing it.

**Comment by pornel** [comment]
Thanks. I've added QoS support (requires 10.10).

**Comment by xorgate** [comment]
This seems a very sensible request to me. 

It might be better to have ImageOptim run slower, if speed is not the main issue. A responsive system is important to do other tasks

**Comment by pornel** [comment]
Does 1.6.1 work better for you?

**Comment by pornel** [comment]
I know there's an OS X issue that makes GUI very slow: #141  Apart from that on the current versions of OS X ImageOptim asks system to be ran with low priority.
