### ISSUE TITLE
File Inspector for Chunk Tweaking 

### ISSUE THREAD

**Issue by Crissov** [ImageOptim/ImageOptim#121]
Applications like [TweakPNG](http://entropymine.com/jason/tweakpng/) (Windows-only) allow inspection and alteration of chunks without a hex editor and without using a command line interface. I wish that was possible in Image Optim, too.

While the main purpose of Image Optim is to automatically minimize a bunch of files thrown at it, optimizing – as in the app’s name – the files may include some additional manual tweaks. Editing chunks directly is usually not available in graphic image editors and as far as I know there is no dedicated OS X tool for that either.

**Comment by pornel** [comment]
I agree it'd be a useful tool, but it doesn't seem to fit focus of ImageOptim, which is supposed to be simple and automatic.

**Comment by Crissov** [comment]
Yes, this should probably be a separate tool.
