### ISSUE TITLE
Fonts should use monospace numbers on 10.11

### ISSUE THREAD

**Issue by ZevEisenberg** [ImageOptim/ImageOptim#124]
El Capitan introduced San Francisco, which has proportional numbers by default. The text in the columns should use monospace numbers so they all line up in neat columns.

![screen shot 2015-12-29 at 10 41 41 am](https://cloud.githubusercontent.com/assets/464574/12036979/e2782bda-ae18-11e5-81e0-ff748bef2033.png)

If you don't know how to enable monospace numbers, check out the "Number Spacing" section of [this blog post](http://www.raizlabs.com/dev/2015/08/advanced-ios-typography/). It's using Swift on iOS, but the same principles apply on the Mac in Objective-C.

**Comment by pornel** [comment]
Thanks. I'm aware of this issue, but currently monospace number support is 
broken in Xcode's IB, rdar://22032973

**Comment by ZevEisenberg** [comment]
You could always do it in code. There aren't that many cells, right? (Only semi-trolling.)

**Comment by pornel** [comment]
@ZevEisenberg could you help me by making a pull request?

**Comment by ZevEisenberg** [comment]
@pornel as requested, and only 187 days late.
