### ISSUE TITLE
ImageOptim website design suggestions

### ISSUE THREAD

**Issue by pornel** [ImageOptim/ImageOptim#129]
I'm thinking about refreshing design of the site. Here's my first take:

![screen shot 2016-02-03 at 11 41 49](https://cloud.githubusercontent.com/assets/72159/12781327/985aca84-ca6b-11e5-9758-c12b7dea8dd8.png)

----

and here's another attempt with perhaps a bit over-the-top colors :)

![screen shot 2016-02-03 at 11 46 45](https://cloud.githubusercontent.com/assets/72159/12781382/fa562b8e-ca6b-11e5-9c19-30b31cc125dd.png)

What's good about it? What can be improved?

**Comment by rowanbeentje** [comment]
In the lower version, I like the new links across the top.  I like the updated screenshot!  I feel the icon+title in the top right shouldn't have opacity even if the links do.

I think I prefer the old three-column layout for feature blurbs - the new one *should* be clearer given the emphasis, I just find it harder to read...

Does nobody donate? :)

**Comment by JamieMason** [comment]
I prefer the first one, but I think both would be improved if the body font-size was bigger (16px maybe).

Totally subjective, feel free to ignore me :)

**Comment by focusaurus** [comment]
Agree the 2nd one's colors are over the top. First one design-wise looks a little too close to an example from a "sites built with this CSS framework" portfolio. I'd want the text that answers basics questions like "What is ImageOptim?" and "What does it do?" in big font somewhere very prominent.

**Comment by vmdanilov** [comment]
I suggest to make it clean and simple.

Key elements:

1. Flexible 12-column grid with 30 px column gutter.
2. Font: 300 16px/1.5 "Helvetica Neue", Helvetica, Arial, sans-serif
3. Generous spacing of 2-3 line heights.
4. Line length of no more than 45–90 char­ac­ters.

Here's a mockup just to illustrate.

![imageoptim-landing-page](https://cloud.githubusercontent.com/assets/3129436/12849474/d86887d0-cc30-11e5-9b70-f9ad11a50979.png)

**Comment by pornel** [comment]
ooooh. Neat!

**Comment by vmdanilov** [comment]
This is just a very generic design. The key elements and the structure are not unique at all. The font combo is the only non-sucky option without using custom fonts. Even line icons are borrowed from Apple website and iOS. I don't want to go into details but if you have questions, I have answers.

Don't take it literally, of course. [Bootstrap](https://github.com/twbs/bootstrap) might be a good start for the grid and basic typography rules.

Here I added some more details. Colors are taken from the app icon. The copy will define final header sizes and spacing.

![imageoptim-landing-page](https://cloud.githubusercontent.com/assets/3129436/12865980/b863979c-ccce-11e5-87d8-30c9c1c7e55d.png)

**Comment by pornel** [comment]
I've implemented a mix of the designs:

https://imageoptim.com/new/

[![screen shot 2016-04-13 at 13 42 33 1](https://cloud.githubusercontent.com/assets/72159/14493534/d0bdf056-017d-11e6-8c1d-351ce2a68ea3.jpg)](https://imageoptim.com/new/)

it gets less and less coherent as it goes down the page :)

I've included a sidebar. I like its functionality, but I don't like how it looks. Can you mock up a better design?

**Comment by pornel** [comment]
I've open-sourced the new site's code:

https://github.com/ImageOptim/website

it's a pretty neat setup with browsersync, so check it out (once you run npm start): 

http://localhost:3000/versions.html


^ I'm looking for ideas how to make small version of the header, especially for the page about non-Mac versions of ImageOptim, so it shouldn't have the screenshot on it:

**Comment by pornel** [comment]
So the new design is live. Feel free to file bugs or post suggestions here.
