### ISSUE TITLE
Pre-Yosemite icons

### ISSUE THREAD

**Issue by Eitot** [ImageOptim/ImageOptim#131]
f540e36a66734a8d7fd6169dd9e6b985a542e6b0 replaced the rich icons with the current flat ones. Is it possible to bundle both and show the old ones for versions poor to Yosemite? I was thinking of throwing them into asset catalogues for a PR, but it seems that they are used for the static help files too. Anyway, I am currently unable to build the Xcode project due to persistent fatal errors. Not sure why it doesn’t work anymore.

**Comment by pornel** [comment]
1. It may be possible, but I'm not sure if it's worth the complexity. Old systems are a shrinking minority.

2. Please post the errors so I may help.
