### ISSUE TITLE
xcode compile error

### ISSUE THREAD

**Issue by hazbolaKor** [ImageOptim/ImageOptim#143]
1.

../scripts/fetch-submodule ../Sparkle && touch ../Sparkle/Sparkle
../scripts/fetch-submodule: line 10: lockfile: command not found
fatal: Not a git repository (or any of the parent directories): .git
rm: /Users/hckim/Downloads/ImageOptim-master: is a directory
make: *** [../Sparkle/Sparkle] Error 128
Command /usr/bin/make failed with exit code 2

2.
../scripts/fetch-submodule src && touch src/jpeglib.h
../scripts/fetch-submodule: line 10: lockfile: command not found
fatal: Not a git repository (or any of the parent directories): .git
rm: /Users/hckim/Downloads/ImageOptim-master: is a directory
make: *** [src/jpeglib.h] Error 128
Command /usr/bin/make failed with exit code 2

os : os x el capitan
xcode : 7.3 

please ...

**Comment by pornel** [comment]
Sorry, looks like the script that gets dependencies has rotten. 

You can work around it by running:

    git submodule update --init --recursive

in the top level directory.

**Comment by pornel** [comment]
I hope the above solves the problem
