### ISSUE TITLE
Automator action

### ISSUE THREAD

**Issue by pathawks** [ImageOptim/ImageOptim#147]
It would be cool to have an Automator action to optimize given images.

**Comment by pornel** [comment]
Would you be able to add it?

Perhaps as a wrapper for CLI? https://imageoptim.com/command-line.html

**Comment by pathawks** [comment]
It doesn't look like there is a way to specify any options via the CLI.

_Ideally_, an Automator action would be able to specify some instance specific settings (lossless vs lossy, which compressors to use, etc) that would be independent of whatever is set in the ImageOptim preferences?

**Comment by pornel** [comment]
I think I can add command line switches for most options in ImageOptim.

In Xcode there's a template for an automator action that wraps a shell command, so hopefully these two could be used together.

**Comment by selrond** [comment]
Please! This would be amazing

**Comment by mujisashi** [comment]
Just wondering if there's any work that's been done here. I'm with @selrond -- SO amazing! 

Thank you for this amazing app!

**Comment by pathawks** [comment]
Sorry, I've not had time to work on this, and probably won't for the foreseeable future.

**Comment by karlhorky** [comment]
Here's an Automator workflow that worked for me.

To install as a service that will appear under right click -> Quick Actions, just unzip to `~/Library/Services/`.

[ImageOptim.workflow.zip](https://github.com/ImageOptim/ImageOptim/files/3108912/ImageOptim.workflow.zip)

<img width="612" alt="Screen Shot 2019-04-23 at 19 53 07" src="https://user-images.githubusercontent.com/1935696/56604112-8abaa900-6601-11e9-96ee-6b4b6184c9f0.png">

<img width="476" alt="Screen Shot 2019-04-23 at 19 54 56" src="https://user-images.githubusercontent.com/1935696/56604200-bccc0b00-6601-11e9-8e6b-d9b42a7e882d.png">

---

And a bonus workflow to resize to 800px width first before running ImageOptim:

[Resize to 800px width + ImageOptim.workflow.zip](https://github.com/ImageOptim/ImageOptim/files/3108968/Resize.to.800px.width.%2B.ImageOptim.workflow.zip)

Edit: Also available in [my `dotfiles`](https://github.com/karlhorky/dotfiles/tree/main/automator-workflows/quick-actions)

**Comment by karlhorky** [comment]
To completely automate it, Automator can also be automatically triggered on new files in a folder using "Folder Actions" (under `File` -> `New` -> `Folder Action`):

![Screen Shot 2019-07-25 at 12 32 45](https://user-images.githubusercontent.com/1935696/61903047-732cde00-aed8-11e9-9fd3-0a82287613cd.png)

**Comment by Varuss73** [comment]
@karlhorky , does this create an action that triggers ImageOptim as soon as a new image is seen in the designated folder? If so, I would kindly ask you to refresh the alternate download location. I have been looking everywhere for this specific solutions.
Many thanks in advance!

**Comment by karlhorky** [comment]
@Varuss73 yes, folder actions are automatic. When I create a new screenshot and the file appears in my Downloads folder, it is automatically optimized by ImageOptim.

I've fixed the link above, sorry about the broken link!
