### ISSUE TITLE
Integrate Lepton

### ISSUE THREAD

**Issue by robinwhittleton** [ImageOptim/ImageOptim#154]
Dropbox have open-sourced [Lepton](https://github.com/dropbox/lepton): a lossless JPEG compressor. They’re claiming some decent size reductions on an average corpus. Is this something that could / should be integrated into ImageOptim?

**Comment by pornel** [comment]
Lepton files are sort-of-like ZIP. A compressed file can't be used directly, it has to be uncompressed first.

It would be OK for archiving, but can't be used for publishing/sharing the images, since nobody will have lepton decompressor.

**Comment by robinwhittleton** [comment]
I … completely misunderstood what Lepton did. Sorry!

**Comment by alvarow** [comment]
It would however be a cool feature to be able to either specify a lepton binary or use a builtin one and offer an option to archive images before optimizing them, or simply archive it.
