### ISSUE TITLE
Canvas trimmer for transparent images?

### ISSUE THREAD

**Issue by ylluminate** [ImageOptim/ImageOptim#158]
I would very much like to have a function that can be ticked right in the front end user interface that would enable ImageOptim to trim off the extraneous transparent portions of the canvas.  Could you please implement this?

**Comment by ylluminate** [comment]
It seems that perhaps this could do the trick: 
```
gm convert input.png -trim +repage output.png
```

**Comment by pornel** [comment]
I think editing of images is beyond scope of this app. It's not something that can be done by default, and the UI doesn't have room for other tasks.

**Comment by ylluminate** [comment]
This doesn't have to do with editing of images, it's a simple checkbox: 
![example](https://cl.ly/26431U1x3S1q/remove%20excess%20transparency.png)

**Comment by pornel** [comment]
No, sorry. That's a very prominent location for very obscure feature.

**Comment by ylluminate** [comment]
No, it's really not a prominent location and it is most certainly not obscure.  By default it would be off / unchecked.  There is certainly more than enough blank space there for that to fit in without any problem whatsoever, further the UI labeling can be toned down to a degree that will make it not prominent by simply choosing a grey coloring of the text that makes it not as high a priority as other items.  Having gotten 3 votes within just 30 minutes of posting [here](http://softwarerecs.stackexchange.com/questions/35418/drag-drop-canvas-trimmer-for-transparent-pngs) certainly shows some interest in such a functionality.

**Comment by pornel** [comment]
I have no doubt that this feature is very useful for you, and you wouldn't mind having a UI element. However, image editing is not image optimization, so I think adding it would not fit ImageOptim's goal of being simple and doing one thing well.

So sorry, I won't implement it. The app is free under GPL, so if you really like to see this feature, you can implement it (or convince someone else to implement it) in a fork.
