### ISSUE TITLE
App name not in system-language in Spotlight

### ISSUE THREAD

**Issue by sushinger** [ImageOptim/ImageOptim#164]
When I open ImageOptim by using Spotlight on OSX, the app name is displayed in Japanese (or Korean?) language instead of English (or German, which is my default system language).

As you can see on the screenshot below.
Is there a way how I can change the name displayed correctly?

![imageoptim-letters](https://cloud.githubusercontent.com/assets/3510329/18263748/80840150-740c-11e6-8afc-14e7d2d91f7e.png)

**Comment by pornel** [comment]
Go to System Preferences -> Languages and delete Japanese from the list of languages.

**Comment by sushinger** [comment]
Perfect, thank you :)
