### ISSUE TITLE
Feature: Preserve colour depth

### ISSUE THREAD

**Issue by ace-dent** [ImageOptim/ImageOptim#165]
Sadly some PNG colour depths are poorly supported (still). For interoperability it can be useful to keep a PNG as RGBA and not reduce the colour depth / bpp- at the obvious cost of compression. It would be nice to add this Preference under `General > Metadata and Color profiles` perhaps named: Keep PNG color depth ?

**Comment by ace-dent** [comment]
In fact, perhaps it should be `Fix PNG to 32bpp color depth (RGBA)` ?
This would adjust previously optimised images back to RGBA before applying other lossless compression steps. One reason for my request, is that I have previously optimised the thousands of icons that are used in LibreOffice for file size. However, during profiling it was found that RGBA formatted PNG images could be decoded more rapidly to build the UI. Now all icons are unoptimized... :-(

**Comment by pornel** [comment]
Hmmm, such problems keep popping up, although different users have different edge cases.

I'm concerned about loss of compression effectiveness. What pixel format are you getting and how slow it is?

For `RGB` vs opaque `RGBA` the file size may be similar, but for 8-bit indexed vs RGBA the difference is huge (3 times larger files).

From speed point of view usually disk access and gzip decoding are the slowest parts. OTOH pixel type conversion is trival and parallelizable, and can be done on line-by-line basis so it fits in cache — it should be almost free. So it'd expect smaller file in less optimal pixel format to still come out ahead.

**Comment by ace-dent** [comment]
There may be a partial solution using existing Preferences ...(?)

- Check 'Strip PNG metadata'.
- Deselect all PNG encoders, except 'Zopfli' and 'AdvPNG' which only work on the Deflate stream and not the lower level pixel encoding.

This will maintain bit depth / colour depth / bpp - but provides only minimal compression. Still better than default output from most encoders.

**Comment by kornelski** [comment]
I'm going to close this. If you have a broken/fragile PNG reader that cares about unused bits in a file, you should fix your reader or don't optimize images.
