### ISSUE TITLE
Preserving dimensions when changing DPI

### ISSUE THREAD

**Issue by simonrob** [ImageOptim/ImageOptim#166]
I'm using ImageOptim for several JPEG files created at 300 DPI. When ImageOptim processes these files, it changes them to 72 DPI. However, in the process the image dimensions end up being larger.

See, for example the following files (assuming GitHub doesn't itself optimise/alter files too much). Open both in Preview, then go to Tools > Adjust Size: original.jpg is 1x1in; optimised.jpg is 4.17x4.17in

I'm not really familiar with image compression, so normalising to 72DPI might be an efficient way to preserve quality at the expense of real-world dimensions (pixel dimensions are of course preserved). If so, could a future version include a preference to selectively disable DPI changes?

Original:
![original.jpg](https://cloud.githubusercontent.com/assets/934006/18476249/306fb35c-79c1-11e6-8ba1-9ce475af6065.jpg)

Optimised:
![optimised.jpg](https://cloud.githubusercontent.com/assets/934006/18476250/30704830-79c1-11e6-93bc-bcf06b245728.jpg)

**Comment by pornel** [comment]
ImageOptim is mainly aimed at publishing on the web, where DPI is a fiction. 

If you need DPI metadata preserved for DTP software, then uncheck "Strip JPEG metadata" in Preferences.

**Comment by simonrob** [comment]
Ok, thanks - will do that in future for non-web images.

**Comment by vladzaets** [comment]
Hi. The same issue with png files, but unchecking "Strip PNG metadata" doesn't help.

**Comment by kornelski** [comment]
Thanks for the report. I'll check that out.

**Comment by leoafarias** [comment]
Yes same issue here. Added a PNG at 300 DPI, unchecked the Strip PNG metadata. But it still displays 72DPI
