### ISSUE TITLE
Crashes after checking update, closing and reopening

### ISSUE THREAD

**Issue by mathbunnyru** [ImageOptim/ImageOptim#170]
If I check for updates, then close the app, next 1 or 2 times, the app crashes after the launch.
OS: macOS Sierra 10.12
ImageOptim: 1.6.1

**Comment by pornel** [comment]
Can you post (or email me) the crash log?

**Comment by mathbunnyru** [comment]
@pornel I reinstalled the app (including deleting settings), and the problem seems to be gone. Thanks!
