### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by tobireif** [ImageOptim/ImageOptim#171]
Thanks for ImageOptim!

I currently use it on Mac OS, but I might switch to Windows at some point, so it would be great if ImageOptim would be available for Windows as well.

**Comment by pornel** [comment]
Sorry, ImageOptim app depends too much on Mac-only system libraries and can't be ported.

See alternatives: https://imageoptim.com/versions.html

**Comment by douglasjunior** [comment]
I love the mageOptim and I used a lot of time, but sometimes I need to use it on Linux or Windows too, so I just created an Electron based tool https://github.com/douglasjunior/emage
