### ISSUE TITLE
auto running?

### ISSUE THREAD

**Issue by tvalleau** [ImageOptim/ImageOptim#175]
Don't see this elsewhere, but for me, if I have anything at all highlighted when I run ImageOptim, it's entered into the window and -immeidately- begins trying to compress it.

I have to be extremely careful to have nothing selected. I was going to live with it until the day I happened to have an application highlighted. IO started running thru the app, optimizing its internal icons, images and other graphics.

Not "a good thing."  I assumed there was an "auto run" pref somewhere, but if there is, I cannot find it.

**Comment by pornel** [comment]
How do you run ImageOptim?

**Comment by tvalleau** [comment]
Oh my gosh... that never occurred to me. I use a launcher (OpenMenuX) 
and it was set to open selected items. Never seems to do it with other 
apps, so I just missed it.

Sorry for the wasted bandwidth!  :-)

Happy Holidays!

Kornel wrote:

**Comment by pornel** [comment]
Ah, OK :)
