### ISSUE TITLE
Beta download?

### ISSUE THREAD

**Issue by henderea** [ImageOptim/ImageOptim#177]
I'm unable to find a download or changelog link for the beta releases on the website any longer.  What happened to that?

**Comment by pornel** [comment]
I've renamed it to "What's new?" https://imageoptim.com/changelog.html

**Comment by henderea** [comment]
Thanks for the answer.  I was aware of the regular changelog, but I remember there being a separate beta changelog before so I was asking about that one.  But if there's no current beta build, then I guess a beta changelog doesn't need to be added in.

I've been on the beta channel for a while, and it's currently at 1.6.4a3, and the current release build is at 1.6.4.  Is there any difference between those that would make it worth it to switch to the release build for now, or are they basically the same thing?

**Comment by pornel** [comment]
They are the same thing.
