### ISSUE TITLE
Auto Update Partially Broken

### ISSUE THREAD

**Issue by TwisterMc** [ImageOptim/ImageOptim#181]
I've been running ImageOptiom for quite a while now and it never tells me that there is a new version available even though it checks on startup. I've started manually checking by hitting the 'Check For Updates..." option and then it tells me that there is a new version and the update downloads and installs just fine.

Is it just me? 

MacBook Pro (Retina, 15-inch, Mid 2015) - MacOS 10.12.2 (16C67)

**Comment by nataniko** [comment]
me too

**Comment by pornel** [comment]
Usually it auto-updates and installs the update when you quit the app. Do you use it in a way that would break it?

**Comment by TwisterMc** [comment]
Not that I'm aware of. I don't have this issue with any other Mac app.

**Comment by pornel** [comment]
I suspect there are two issues at play:

- Sparkle downloads updates in the background and installs them on quit. So if you check for updates manually, you may see a new version is available, but it would be installed automatically anyway if you quit the app.

- If you start and quit the app too quickly (e.g. by using it from command line like ImageOptim-CLI), then it won't have enough time to download and install auto-updates.

**Comment by TwisterMc** [comment]
How about a visual indicator that says that there is a new version available so we know not to quit the app? Or maybe when we close the ImageOptium window, it doesn't quit the app? That way it's open in the background and can do the updating?

I can see that since it doesn't take long to compress an image, that I'd open and close the app before the download completes.

**Comment by TwisterMc** [comment]
Actually, I just opened the app and noticed that 'Check for updates' was greyed out. So I waited and nothing happened. Then I checked again and I was able to "Check for Updates," When I did, it said there was a new version available. and it downloaded and installed it. So I don't feel it's a user error.

**Comment by justinmayer** [comment]
I can confirm this behavior on two different Macs running Sierra (10.12.2). The "Check for updates" option is initially grayed out, and then seems to become functional within about five seconds after launch.

**Comment by pornel** [comment]
The next update will have improved behavior. It'll tell you when it's waiting to install auto-update when you check manually.
