### ISSUE TITLE
png.h not found

### ISSUE THREAD

**Issue by aolin480** [ImageOptim/ImageOptim#183]
I went ahead and cloned this recursively, and it starts to load fine, but then I get the following error and the build fails

`ImageOptim/pngcrush/pngcrush.c:1474:10:` 'png.h' file not found with <angled> include; use "quotes" instead`

I tried to rubber duck this error as much as I could, but couldn't find anything :(

Any help would be awesome!

Thank you!

**Comment by pornel** [comment]
It'll work if you use Xcode's suggestion and change `<png.h>` to `"png.h"`

**Comment by aolin480** [comment]
Naturally, I did change it to quotes, but then I received the following error:

![image](https://cloud.githubusercontent.com/assets/1616101/22002034/5012ccc6-dc0e-11e6-810b-837a117b4748.png)


Thanks in advance!

**Comment by pornel** [comment]
*Sigh*. There's an oddity/big in Xcode running Make. Sometimes it never patches optipng, sometimes it patches pngcrush twice.

Go to pngcrush subdirectory and run

``sh
make clean
make
```

**Comment by aolin480** [comment]
Thanks for your help on this. I was able to successfully build, but I also had to go into optipng, as well as the svgo folder and run:

```
git pull
make clean
make
```

and that fixed the other modules that errored out. I successfully built the app.


Thanks again!
