### ISSUE TITLE
[FEATURE] Support for GPU processing

### ISSUE THREAD

**Issue by tsilcher** [ImageOptim/ImageOptim#184]
I'd like to suggest that you consider adding support for GPU processing of images which would increase the speed considerably compared to CPU. I hope you consider it.

Thanks.

**Comment by pornel** [comment]
Which tools/algorithms would be suitable for GPU?

**Comment by daviddegliame** [comment]
I almost think this answer is not a real question …
Are there any difficulties in using the GPU on our Macs?

I'm curious...

**Comment by pornel** [comment]
It's was not a real answer, because the question was based on an assumption that wasn't quite true.

GPUs do not make things automatically faster. GPUs have high throughput only for specific types of trivially parallel problems that can be expressed as lots of identical, independent computations with almost no conditional code.

Most compression algorithms are completely linear, consisting almost entirely of inter-dependent conditional code which is the worst case scenario for a GPU.

**Comment by pornel** [comment]
But since it was asked one thing changed: ImageOptim now contains Guetzli, which does a lot of image analysis that is parallelizable, and there is an old version of Guetzli that uses GPU, so I may be able to bring that one.

**Comment by daviddegliame** [comment]
Thanks for your messages, so I didn't think of it that way. 
I understand better how it works …
( in France we said sentence like —a poor translate— "I will go sleeping less idiot this night" )

For my own, I'm ok with any techniques that let me control the average load of my machine.
while i'm sent large amount of files in ImageOptim, I'm ok to wait for more many second if, in parallel, I can continue to work. It's a kind of difficult when all process take 100% of machine capacity 
for exemple, why not have option button for selecting how many processes imageOptim can use. like it's can working with only 2 or 3 of my 4core processor, or, having a pause button, or … Another idea …

**Comment by tsilcher** [comment]
Thanks for the response and I appreciate the time and effort you are putting into it.

**Comment by custa1200** [comment]
> for exemple, why not have option button for selecting how many processes imageOptim can use. like it's can working with only 2 or 3 of my 4core processor, or, having a pause button, or … Another idea …

I would also like the ability to limit the number of cores. I am wanting to do a lot of compression in the background while I can still use another tool (which currently does not work correctly if there is no CPU available)

**Comment by kornelski** [comment]
GPU isn't happening.
