### ISSUE TITLE
Mail extension does not optimize small(er) sizes

### ISSUE THREAD

**Issue by darkv** [ImageOptim/ImageOptim#185]
The mail extension optimizes images you include in an email. As soon as you change the image size setting for that email to anything other than _Actual Size_ you get a smaller (by image dimensions) version of the image which is not optimized. Even if you choose to optimize that one with ImageOptim again you don't get any improvement as apparently only the original size is processed.

Tested on OS X 10.11.6

**Comment by pornel** [comment]
I don't think I can fix it. The extension optimizes the file that Apple Mail gives it. Apparently Apple Mail chooses to give only the original size.

**Comment by darkv** [comment]
Too bad :-(
But thanks for checking.
