### ISSUE TITLE
Confusing "Autoupdate wants to make changes" popup

### ISSUE THREAD

**Issue by RJWoodhead** [ImageOptim/ImageOptim#190]
After I exited ImageOptim (and a few other apps) I got a popup saying "Autoupdate wants to make changes" (or somesuch) and asking for admin privileges.

Needless to say this ambiguous message raised a red flag.

I did a little googling and it seems to occur when an app uses the Sparkle framework and does not properly configure it with a custom name. This issue explains more: https://github.com/sparkle-project/Sparkle/issues/470

ImageOptim apparently includes Sparkle, and doing a manual update (from menu item) results in the same popup.

Should be an easy tweak.

**Comment by pornel** [comment]
Thanks for the report. I'll fix it in the next version.
