### ISSUE TITLE
help. i wanna solve this error

### ISSUE THREAD

**Issue by Jame-suu** [ImageOptim/ImageOptim#195]
<img width="758" alt="2017-03-18 2 30 59" src="https://cloud.githubusercontent.com/assets/26489961/24055529/b331885c-0b83-11e7-8b2d-7e9f33e326cc.png">

I was using Optim app for 3month.
But oneday suddenly app doesn't work.
I really need this app.
I want to know how to solve this problem and why this problem occured.
please anyone help me

**Comment by pornel** [comment]
You will see more about the problem if you hover your mouse cursor over the (!) icon.

You can also see more details in Console.app.

**Comment by Jame-suu** [comment]
Thanks for reply my help.
But When I move cursor over the (!) icon it just say 
"Can't start Jped Optim" or "Can't Start GIF Sicle"
Thats all TT. 

and I'm ashamed to ask you,
I dont know What Console.app is.
How can i download it or use it

**Comment by pornel** [comment]
Every Mac has Console.app. You can find it in your Spotlight search. 

The error may be related to #192

**Comment by Jame-suu** [comment]
I read #192.
and my mac ox ver. 10.8.5
so I deleted Optim and downgraded Ver. 1.6.5
but problem still occured.

also I use Console but i dont know what it says.
Can you solve this problem? OMG

================Console Says this things====================
17. 3. 21. 오전 9:37:58.179 powerd[18]: PID 18(powerd) TimedOut InternalPreventDisplaySleep "com.apple.powermanagement.delayDisplayOff" 06:29:55  id:0xd0000248c Aggregate:0x402042
com.apple.message.domain: com.apple.powermanagement.Assertions
Process: 18
Action: TimedOut
AssertionName: InternalPreventDisplaySleep
com.apple.powermanagement: pmlog

17. 3. 21. 오전 9:37:58.179 powerd[18]: PID 18(powerd) Released InternalPreventDisplaySleep "com.apple.powermanagement.delayDisplayOff" 06:29:55  id:0xd0000248c Aggregate:0x402042
com.apple.message.domain: com.apple.powermanagement.Assertions
Process: 18
Action: Released
AssertionName: InternalPreventDisplaySleep
com.apple.powermanagement: pmlog

17. 3. 21. 오전 9:37:58.179 powerd[18]: Summary- Aggregate:0x42 Using Batt
com.apple.message.domain: com.apple.powermanagement.Assertions
Action: Summary
com.apple.powermanagement: pmlog

17. 3. 21. 오전 9:41:28.634 Apple80211 framework[35556]:  
com.apple.message.domain: com.apple.wifi.timeout.scan
com.apple.message.signature: Success
com.apple.message.result: pass
com.apple.message.value: 702.000000
com.apple.message.summarize: YES

17. 3. 21. 오전 9:41:40.325 Apple80211 framework[35556]:  
com.apple.message.domain: com.apple.wifi.timeout.scan
com.apple.message.signature: Success
com.apple.message.result: pass
com.apple.message.value: 687.000000
com.apple.message.summarize: YES

17. 3. 21. 오전 9:58:29.609 storeagent[12140]: com.apple.message.domain: com.apple.MacAppStore.download_done
com.apple.message.start_reason: purchase
com.apple.message.was_staged: tbh
com.apple.message.bundle_id: com.kakao.KakaoTalkMac
com.apple.message.error_description: n/a
com.apple.message.local_caching: not available
com.apple.message.error_code: 0
com.apple.message.power_state: on
com.apple.message.cancelled: false
com.apple.message.result: pass
com.apple.message.delta: did not try

17. 3. 21. 오전 9:58:33.295 powerd[18]: PID 35670(helpd) Created BackgroundTask "com.apple.helpd.sdmbuilding" 00:00:07  id:0xc000024d5 Aggregate:0x42
com.apple.message.domain: com.apple.powermanagement.Assertions
Process: 35670
Action: Created
AssertionName: BackgroundTask
com.apple.powermanagement: pmlog

17. 3. 21. 오전 10:01:06.321 powerd[18]: PID 35556(Google Chrome) Created NoIdleSleepAssertion "Download in progress" 00:00:05  id:0x1000024d8 Aggregate:0x42
com.apple.message.domain: com.apple.powermanagement.Assertions
Process: 35556
Action: Created
AssertionName: NoIdleSleepAssertion
com.apple.powermanagement: pmlog

17. 3. 21. 오전 10:01:11.913 powerd[18]: PID 35556(Google Chrome) Released NoIdleSleepAssertion "Download in progress" 00:00:10  id:0x1000024d8 Aggregate:0x42
com.apple.message.domain: com.apple.powermanagement.Assertions
Process: 35556
Action: Released
AssertionName: NoIdleSleepAssertion
RetainCount: 0
com.apple.powermanagement: pmlog

17. 3. 21. 오전 10:02:28.794 syspolicyd[739]: assessment granted for ImageOptim1.6.5.tar.bz2 by _XProtect
com.apple.message.domain: com.apple.security.assessment.outcome2
com.apple.message.signature2: bundle:UNBUNDLED
com.apple.message.signature3: ImageOptim1.6.5.tar.bz2
com.apple.message.signature5: UNKNOWN
com.apple.message.signature4: 3
com.apple.message.signature: granted:_XProtect

17. 3. 21. 오전 10:05:55.368 System Preferences[35772]: com.apple.message.domain: com.apple.systempreferences.3rdpartycount
com.apple.message.3rdpartycount: 2

========================================================

TT

**Comment by pornel** [comment]
From the log it looks like you haven't run ImageOptim 1.6.5 yet, so I don't see what is failing.

Please do this:

1. Open Console.app. Press "clear display" toolbar button.
2. Open ImageOptim.app
3. Drop images to ImageOptim
4. Copy log from the Console.app. Only parts that mention ImageOptim are needed.

**Comment by Jame-suu** [comment]
Sorry for bothering you.
Its the message of part that you mentioned.
=============================
- ImageOptim[37192]: Unknown class 'FadeView', using 'NSView' instead. Encountered in Interface Builder file at path /Users/rauvis/Desktop/ImageOptim1.6.5/ImageOptim.app/
Contents/Resources/Base.lproj/ImageOptim.nib.
- ImageOptim[37192]: Results cache is in /Users/rauvis/Library/Caches/
net.pornel.ImageOptim/Results.db
- ImageOptim[37192]: Can't find working executable for JpegTran - disabling
- ImageOptim[37192]: Can't find working executable for JpegOptim - disabling
- ImageOptim[37192]: Cannot launch jpegoptim
- ImageOptim[37192]: Cannot launch jpegtran

**Comment by pornel** [comment]
Thank you. I need one more bit of information.

1. Open Terminal.app (it's in /Applications/Utilities)
2. Copy & paste this command in and press enter:

       ls -lR  /Users/rauvis/Desktop/ImageOptim1.6.5/ImageOptim.app/Contents/Frameworks/ImageOptimGPL.framework

3. Select all text and copy it here

**Comment by Jame-suu** [comment]
here!
==========================================
Last login: Wed Mar 22 21:38:04 on ttys000
ijewon-ui-MacBook-Pro:~ rauvis$ ls -lR  /Users/rauvis/Desktop/ImageOptim1.6.5/ImageOptim.app/Contents/Frameworks/ImageOptimGPL.framework
total 0
-rw-r--r--  1 rauvis  staff    0  1 27  2014 ImageOptimGPL
-rw-r--r--  1 rauvis  staff    0  1 27  2014 Resources
drwxr-xr-x  4 rauvis  staff  136  3 21 10:02 Versions

/Users/rauvis/Desktop/ImageOptim1.6.5/ImageOptim.app/Contents/Frameworks/ImageOptimGPL.framework/Versions:
total 0
drwxr-xr-x  5 rauvis  staff  170  3 21 10:02 A
-rw-r--r--  1 rauvis  staff    0  1 27  2014 Current

/Users/rauvis/Desktop/ImageOptim1.6.5/ImageOptim.app/Contents/Frameworks/ImageOptimGPL.framework/Versions/A:
total 320
-rwxr-xr-x   1 rauvis  staff  161312  1 27  2014 ImageOptimGPL
drwxr-xr-x  14 rauvis  staff     476  3 21 10:02 Resources
drwxr-xr-x   3 rauvis  staff     102  3 21 10:02 _CodeSignature

/Users/rauvis/Desktop/ImageOptim1.6.5/ImageOptim.app/Contents/Frameworks/ImageOptimGPL.framework/Versions/A/Resources:
total 3152
-rw-r--r--  1 rauvis  staff    1376  1 27  2014 Info.plist
-rwxr-xr-x  1 rauvis  staff   77920  1 27  2014 advpng
-rwxr-xr-x  1 rauvis  staff  158448  1 27  2014 gifsicle
-rwxr-xr-x  1 rauvis  staff   39040  1 27  2014 jpegoptim
-rwxr-xr-x  1 rauvis  staff   41680  1 27  2014 jpegtran
-rwxr-xr-x  1 rauvis  staff  340400  1 27  2014 libimageoptimjpeg.dylib
-rwxr-xr-x  1 rauvis  staff  179776  1 27  2014 liblibpng.dylib
-rwxr-xr-x  1 rauvis  staff   61168  1 27  2014 optipng
-rwxr-xr-x  1 rauvis  staff   96336  1 27  2014 pngcrush
-rwxr-xr-x  1 rauvis  staff  348896  1 27  2014 pngout
-rwxr-xr-x  1 rauvis  staff   85328  1 27  2014 pngquant
-rwxr-xr-x  1 rauvis  staff  159392  1 27  2014 zopflipng

/Users/rauvis/Desktop/ImageOptim1.6.5/ImageOptim.app/Contents/Frameworks/ImageOptimGPL.framework/Versions/A/_CodeSignature:
total 16
-rw-r--r--  1 rauvis  staff  5786  1 27  2014 CodeResources
ijewon-ui-MacBook-Pro:~ rauvis$

**Comment by pornel** [comment]
That is strange. It looks like all the files are in the right place, but ImageOptim can't find them.

Try this version:

https://imageoptim.com/ImageOptim1.7.1a4.tar.bz2

**Comment by Jame-suu** [comment]
OMG TTTTTTTTTT
I installed Optim from that link. 
then.. same problem TT.
anyway Thanks to trying helping me. thanks a lot.
Imageoptim was best app I've ever used.
Even it was better than any app from appstore TT
but It seems to be hard to solve this problem..

**Comment by pornel** [comment]
So I don't know what's going on. If you can, please upgrade Mac OS X to 10.9 or 10.12.

In the meantime, downgrade ImageOptim to an old version that should definitely work with the outdated system:

https://imageoptim.com/ImageOptim1.5.4.tar.bz2

**Comment by Jame-suu** [comment]
Oh my God!!!!!!!!Problem solved!!!!I installed imageOptim 1.5.4 Ver. Then it works!!!Thanks a lot!!!!!!! God bless you!!!! 
------ Original Message ------
Date: Thursday, Mar 23, 2017 02:22:35 AM
