### ISSUE TITLE
error: could not lock config file .git/config: File exists

### ISSUE THREAD

**Issue by liufsd** [ImageOptim/ImageOptim#203]
../scripts/fetch-submodule guetzli && touch guetzli/src
error: could not lock config file .git/config: File exists
fatal: Failed to register url for submodule path 'guetzli/guetzli/guetzli'
Submodule 'guetzli/guetzli' (https://github.com/google/guetzli.git) registered for path 'guetzli/guetzli/guetzli'
Cloning into '/Users/liupeng/Documents/workspace/ImageOptim/guetzli/guetzli'...
Submodule path 'guetzli': checked out '264d83509ac699fc4707cda52dfb7252ad071bac'
Command /usr/bin/make emitted errors but did not return a nonzero exit code to indicate failure

**Comment by pornel** [comment]
There's a race condition in git submodule build. Try building again. If not, clone again, but this time with --recursive option.

**Comment by liufsd** [comment]
and then run it 

/ImageOptim/guetzli/guetzli/guetzli/guetzli.cc:59:14: Use of undeclared identifier 'LIBPNG_WAS_COMPILED_WITH__PNG_NO_SETJMP'

**Comment by liufsd** [comment]
<img width="1117" alt="wx20170405-224935 2x" src="https://cloud.githubusercontent.com/assets/1910405/24711327/34268444-1a52-11e7-9ec9-c9d6250f5b31.png">

**Comment by liufsd** [comment]
HI~  thanks for response~>
so.
how to fix this error ?

**Comment by liufsd** [comment]
clang: error: no such file or directory: '/Users/liupeng/Documents/workspace/ImageOptim/pngquant/src/lib/blur.c'
clang: error: no input files

**Comment by pornel** [comment]
Submodule issue fixed in 44b7c575e0c5c176fa6861ee7f8cee105209548c - try cloning again


As for `LIBPNG_WAS_COMPILED_WITH__PNG_NO_SETJMP`, modify guetzli's code to `#include "pngconf.h"` before `png.h`

**Comment by liufsd** [comment]
yeah~ great work. clone success.
but run error 

```
patch --forward -p1 -d gifsicle < gifsicle-1.89-imageoptim.patch && touch patched
patching file src/gifsicle.c
Reversed (or previously applied) patch detected!  Skipping patch.
8 out of 8 hunks ignored -- saving rejects to file src/gifsicle.c.rej
make: *** [patched] Error 1
Command /usr/bin/make failed with exit code 2
```

**Comment by liufsd** [comment]
<img width="1141" alt="screen shot 2017-04-06 at 8 41 32 am" src="https://cloud.githubusercontent.com/assets/1910405/24732663/e0e17c82-1aa4-11e7-9c3a-0d5d46f0df39.png">

**Comment by liufsd** [comment]
@pornel  hi~ 
i just want use pngquant for my cocoa app demo ,how to work a demo ?

**Comment by pornel** [comment]
Run:

```sh
cd gifsicle;
touch patched
```

The same if you get an error about pngcrush.

**Comment by pornel** [comment]
I've tweaked build files, so you might try pulling or cloning again

**Comment by liufsd** [comment]
Thanks.
Great job.~
I will git clone it and test it.

**Comment by liufsd** [comment]
error: /Users/liupeng/Documents/workspace/ImageOptim/svgo/build/svgo.js: No such file or directory

**Comment by liufsd** [comment]
done ~  thanks.~
