### ISSUE TITLE
separate name for beta version

### ISSUE THREAD

**Issue by monouser7dig** [ImageOptim/ImageOptim#204]
could the beta version be named
"Image Optim beta" to sit along the stable version?

I can rename it manually but guess that is generally accepted to be useful practice (and the top left program name would also match the actual beta vs non beta version)

thanks for consideration

**Comment by pornel** [comment]
Thanks for the suggestion. The name is used in several places in the code, localizations and scripts. It's cumbersome to update it for every release and a bit of work to automate, so I'm reluctant to change it.

**Comment by monouser7dig** [comment]
Ok appreciate that 

Thanks anyway
