### ISSUE TITLE
Add support for Brotli

### ISSUE THREAD

**Issue by levidurfee** [ImageOptim/ImageOptim#220]
Any plans for adding Brotli as an option for compression?

Thanks :)

**Comment by pornel** [comment]
How would that work?

**Comment by levidurfee** [comment]
I'm not sure, but [Brotli](https://github.com/google/brotli) has been implemented using a few different languages.

**Comment by pornel** [comment]
Brotli is a feature of HTTP, used while sending files on the web. It's not currently used by any image format.

So I don't see how ImageOptim could use brotli without becoming a web server.
