### ISSUE TITLE
update error

### ISSUE THREAD

**Issue by ctf0** [ImageOptim/ImageOptim#221]
![screen shot 2017-07-15 at 12 22 39 pm](https://user-images.githubusercontent.com/7388088/28238636-5aac051c-6958-11e7-8d88-485e08fe1b20.jpg)

also the link on the website say v1.7.1 and it still downloads the old v 1.7.0

**Comment by pornel** [comment]
Thanks for the report. I think it's caused by a recent DNS change I've made and should sort itself out withing 24 hours.
