### ISSUE TITLE
Add compatibility for vowel mutation like ä ü ö etc. in german language

### ISSUE THREAD

**Issue by chdhesi0** [ImageOptim/ImageOptim#227]
Hi there,

Your image processor is handling file names really awkwardly. Because when I have some file name with some special characters like -> ä ö ü etc. in German language it's corrupting the file-name and replacing it with different characters. Please detect vowel mutations and prevent the processor from  changing any characters. File name should be same as before. 

Thanks man,

Simon

**Comment by pornel** [comment]
Oh, this absolutely shouldn't be happening.

What version of ImageOptim do you have? What version of macOS?

Can you do this:

1. Open Console.app
2. In Console.app search for ImageOptim
3. In ImageOptim optimize a file with ü, etc.
4. Copy log from Console.app and post it here

**Comment by chdhesi0** [comment]
The case is funny and exhausting too. Because I was using your image processor for a lot of images on an application in live production. I didn't check the file names for sure not. Hehe. Then, suddenly I noticed that all the German vowels are gone in the file name ... replaced with empty spaces etc. Like your app can't handling latin vowels from other languages. That was really a pain in the ass. My application did produce a lot of errors. But you app is just one of the pest on the market don't get me wrong. It's just weird in my personal case. Shouldn't work like that man. ;)

Simon from trainsane

**Comment by pornel** [comment]
I don't understand your comment.

Let me clarify:

* ImageOptim does support Unicode filenames, as far as I can tell. I've tested this, and filenames with spaces, umlauts, CJK characters work fine on my machine.

* if it doesn't work in some cases, I'd like to fix it. I need very precise information from you what exactly fails and where, and in what way. Just saying it's bad is not enough for me to diagnose the problem.

**Comment by rpkoller** [comment]
@pornel tried it on osx 10.11.6 with the latest patches applied along imageoptim 1.7.2. I've tried with a filename for a jpeg file containing ü and ß in the filename and all worked like expected. unable to reproduce the issue on my side. best regards r.

**Comment by pornel** [comment]
Thanks. Feel free to reopen if you find problems.

**Comment by dermatz** [comment]
Have a similar problem in latest version (1.8.0)
Orginal Filename **Mö**gglingen_Bahnhof.jpg
After Compression: **MÖ**gglingen_Bahnhof.jpg

The Umlaut is Uppercase now.

<img width="1003" alt="imageoptim" src="https://user-images.githubusercontent.com/6103201/38412030-b68fe6f4-3988-11e8-911a-a177f2f569e7.png">

**Comment by mcaskill** [comment]
I have a similar issue in 1.8.5 with files containing french accents:

1. Original file name: `marc-andré_10.jpg` (`marc-andr&#xE9;_10.jpg`)
2. After compression: `marc-andré_10.jpg` (`marc-andre&#x301;_10.jpg`)

**Comment by kornelski** [comment]
That change (NFKD-like normalization) is mandatory on macOS's HFS. The file system is unable to store files any differently (it's also a pervasive problem in git, zip, and other cross-platform tools). 

It's technically optional on APFS, but I think Apple still decided to do it for backwards compatibility. I'm using unicode strings everywhere, and I'm not touching normalization myself, so it's the macOS that changes it.

**Comment by mcaskill** [comment]
Hrm. I've performed some additional tests.

I had initially downloaded all the images from the server using Transmit.app (5.2.1 Build 99883) and tried `scp` to download them.

Unfortunately, I can't seem to reproduce the normalization issue I was having a couple of days ago.

Thanks for the explanation, it gave me some directions to explore.
