### ISSUE TITLE
Support for NEF/TIFF RAW file

### ISSUE THREAD

**Issue by aonez** [ImageOptim/ImageOptim#229]
It seems that NEF RAW files are not supported. I've dropped one of those and a orange signal appeared. Also exported it to TIFF and no support either. Is this project just for PNG and JPG sources?

Here an example: [DSC_6484.zip](https://github.com/ImageOptim/ImageOptim/files/1221606/DSC_6484.zip)

Tried to compile the project but had an error on Sparkle make, so I did not really had the chance to debug.

**Comment by aonez** [comment]
No need to do nothing. Thought I can use this app as a batch resizer too. I'm closing it as a duplicate of #48.

**Comment by abdennour** [comment]
+1 
TIFF should be supported
