### ISSUE TITLE
Lossless JPG optimization actually lossy

### ISSUE THREAD

**Issue by jgwidmer** [ImageOptim/ImageOptim#231]
Hi there,

Recently I have been seeing image quality degradation when running JPGs through the tool multiple times despite having lossy minification disabled. I have not noticed it with PNGs, but it is noticeable in JPGs. Before and afters for both JPGs and PNGs are attached. Both were run through ~10 times as a test. The JPG degradation is most noticeable in the bottom of the waves and around the "SHOP NOW" text.

Thanks,
James
[ImageOptimTest.zip](https://github.com/ImageOptim/ImageOptim/files/1244905/ImageOptimTest.zip)

**Comment by pornel** [comment]
Do you have Guetzli enabled?

**Comment by jgwidmer** [comment]
Ah yes I did. That makes sense.

**Comment by pornel** [comment]
Yeah, sorry about that. I should probably explain that option better. Guetzli tries to make loss invisible, but it's not 100% lossless.

**Comment by jgwidmer** [comment]
All good. I was just getting greedy anyway. Thanks for the info!

**Comment by 007** [comment]
Can guetzli be removed from the processing list if you don't check the `Enable lossy minification` checkbox? Seems weird to have that as an option, but that the tool isn't actually lossless.

**Comment by kornelski** [comment]
I'll probably have to change lossy/lossless into more detailed options, because to some people "lossless" means "visually lossless to human eye (but pixels may change)" and some people understand lossless as "sha-1 of pixels remains the same".
