### ISSUE TITLE
List of files from the past appears from times to times to haunt me

### ISSUE THREAD

**Issue by KatkayApps** [ImageOptim/ImageOptim#233]
This is the problem: A few years ago I have used ImageOptim to optimize 1000 images from multiple directories on my disk. That was a bad decision because ImageOptim crashed at the time and the list of files was never processed fully. Somehow this list is stored somewhere, in the twilight zone, and returns from times to times when ImageOptim is called from a Bash Script.

I have a few automator scripts that call ImageOptim from a Bash shell script. This works fine 50% of the time. From times to times, ImageOptim opens with the files Bash sends to it and suddenly the old haunted list of 1000 files is appended to the queue and I have to force quit ImageOptim.

I am sure I have reported this in the past but I cannot find my issue.

At the time someone told me that ImageOptim does not store any list but boy it is stored somewhere and it returns to haunt me.

Can you guys please verify what kind of situation can make that happen?

**Comment by pornel** [comment]
Indeed, ImageOptim does not store the list. 

Perhaps you still have the script that runs it with the 1000 files? ImageOptim searches for files if you launch it with a path to a directory, so maybe your script ends up doing that?

**Comment by KatkayApps** [comment]
No, the case of the 1000 files started differently.
One day I opened ImageOptim and started dragging images to it. I am saying 1000 but it was probably 10K images. After a while I gave up because it was taking too long but at that point ImgOptim was so busy I could not close it, so I force quit.

Then I have these scripts that call ImgOptim. These are a different thing.

What happens is that from times to times, when I run these scripts the image return.

Like I said the images were not sent to ImgOptim by a script. 

Now I am hunted by these images and every time it happens ImgOptim displays the beachball of death and cannot be killed unless by force quit.

By what you said, I think your code is not is not reading particularly from anywhere but perhaps MacOS is reading from some file and passing these images to ImgOptim when it runs.

The scripts that do these were created using automator. They are a service to finder. I select a bunch of files on finder, right click them, services, SCALE IMAGES 50%, that is one of my scripts. So, finder will pass the images to the service created using automator. This service has a initial part that shows a dialog and then runs a code in applescript that will, at the end, call ImgOptim.

This is what I can tell you about the whole thing... 😃

**Comment by pornel** [comment]
it's very likely that the automator "get files" step has the list of files saved.

**Comment by KatkayApps** [comment]
Ok, I thought about that too but in this case the services were already compiled/created (?) by automator and "installed" into Finder. Unless automator puts some code there to to this. Anyway I will close this and keep trying to isolate some steps that can be used to reproduce the "problem"... thanks.

**Comment by pornel** [comment]
Yes, automator does put files hardcoded in the services.
