### ISSUE TITLE
Zopfli Not Correctly Compressing This PNG

### ISSUE THREAD

**Issue by DiegoAce** [ImageOptim/ImageOptim#237]
When Zopfli is enabled this png is not compressed correctly. All other settings are default. The image appears fine when looking at it through Preview on my Mac, but when I load it into my game with stb-image and display it, it is a solid color. Let me know if you need more information.

![knight](https://user-images.githubusercontent.com/19171919/30436748-936fae76-9932-11e7-8f9a-e2a5a279c73f.png)

**Comment by DiegoAce** [comment]
[pngs.zip](https://github.com/ImageOptim/ImageOptim/files/1303511/pngs.zip)
Here's a before and after compression.

**Comment by pornel** [comment]
The files are valid. The image has been optimized by converting from true-color mode to grayscale mode. Perhaps std-image doesn't support grayscale PNGs?

**Comment by DiegoAce** [comment]
Interesting! I see now that any grayscale image is not displayed correctly. I'll look into that. Thanks for the help and thanks for the great program!
