### ISSUE TITLE
Does not play nice with Google Drive File Stream

### ISSUE THREAD

**Issue by aentan** [ImageOptim/ImageOptim#238]
When I drag files from Google Drive File Stream into ImageOptim, the optimization happens initially then I get errors. When I check the folder, the file gets renamed into a hidden file.

Example: drag `myfile.png` into ImageOptim, error occurs.
Result: file gets renamed to `.myfile~imageoptim.png`.

I've turned on "Available Offline" for the relevant files/folders.

**Comment by pornel** [comment]
Interesting. I'll have a look.

**Comment by aentan** [comment]
Thanks man!

**Comment by EricPlatt** [comment]
I've got the same issue with Google Drive File Stream Version: 25.1.76.2046 on macOS 10.12.6.

**Comment by pornel** [comment]
Is there a way to install Google Drive File Stream without belonging to a school/workplace that uses it?

**Comment by EricPlatt** [comment]
You should have just received an email to a test folder. You may need to create a google account to use it. There are two versions of Google Drive, that i know about. It worked fine in the old version. Be sure to download the new app. Thanks.

**Comment by pornel** [comment]
Thanks

**Comment by pornel** [comment]
Fixed in 1.7.4a1

**Comment by voicrose** [comment]
Thanks!

**Comment by mariovass** [comment]
Where can I find 1.7.4a1 for mac?

**Comment by kornelski** [comment]
All versions are here https://imageoptim.com/changelog.html
