### ISSUE TITLE
Output stats on command line

### ISSUE THREAD

**Issue by grischard** [ImageOptim/ImageOptim#243]
Running ImageOptim on the command line is currently silent. It would be very useful for automations if you could get the stats in the output, like you get at the bottom of the window in interactive mode.

Expected output:

```
$ /Applications/ImageOptim.app/Contents/MacOS/ImageOptim *.png
Saved 122 KB out of 3 MB. 7.2% per file on average (up to 57.6%)
$
```

**Comment by pornel** [comment]
Try https://github.com/JamieMason/ImageOptim-CLI/ which adds nice output.
