### ISSUE TITLE
 Optionally convert GIF <-> PNG, whichever is smaller

### ISSUE THREAD

**Issue by biziclop** [ImageOptim/ImageOptim#245]
Another in the “Optionally convert” series:
If it's losslessly doable, then optimise both way, then choose the smaller one.
Maybe replace or add the new extension.

And thants for the great utility!

**Comment by Saklad5** [comment]
GIF is a terrible format. It is extremely unlikely that a GIF could store the same image using less space than a PNG, and I believe it is outright impossible if your image has more than 256 colors.

Quite frankly, I’d always using GIF whenever possible if I were you. [It’s not even good for short animated clips!](https://calendar.perfplanet.com/2017/animated-gif-without-the-gif/)

**Comment by pornel** [comment]
Indeed, GIF has very weak compression. It only has a smaller header than PNG, which makes 1x1 pixel image a little bit smaller. So overall the potential saving of this optimization is ~100 bytes or so.

**Comment by biziclop** [comment]
Ok, I understand, and thanks for the link, @Saklad5 !
