### ISSUE TITLE
Add WebP encode and decode support

### ISSUE THREAD

**Issue by byronpolley** [ImageOptim/ImageOptim#249]
As this is the future of images on the web I think it would be a nice feature and could use the library here: https://developers.google.com/speed/webp/

You can close the issue if there is no plans for it.

**Comment by kornelski** [comment]
It's an 8-year-old format, based on a 12-year-old codec that lost in the market to a 15-year-old-cocec. I don't think it's worth supporting. If you're OK serving a non-standard format I suggest using BPG instead, which is a generation more modern and often **50% smaller than WebP**: https://bellard.org/bpg/

Apart from that, there are no WebP optimization tools, and WebP is not safe to use without some form of server-side support or markup changes, so ImageOptim is not a good place to add such complications.

**Comment by byronpolley** [comment]
Thanks for the speedy response. Was unaware of such, Google Chrome web audit continuously asks for the images to be served using this to pass making me believe it was a critical part of web images.

**Comment by CAFxX** [comment]
Maybe it's time to reconsider this decision. WebP *today* is natively [supported by the majority (~73%) of used browsers](https://caniuse.com/#feat=webp), and this number is going to grow in the next months with both [Firefox and Edge working on supporting it](https://www.zdnet.com/article/firefox-and-edge-add-support-for-googles-webp-image-format/).

As much as I would love for the world to converge on BPG, it unfortunately doesn't change the fact that the "more modern" image compression formats that are natively supported are HEIF (Apple world) and WebP (non-Apple world). This still holds even considering that WebP already has a spiritual successor in AVIF.

**Comment by b-b0t** [comment]
@CAFxX I think the devs of this are against WebP so I actually found what I needed with almost an identical interface: https://webponize.org/
