### ISSUE TITLE
SVG becomes blank after optimization

### ISSUE THREAD

**Issue by tomgreep** [ImageOptim/ImageOptim#256]
When optimizing attached svg with the svgcleaner option turned on, the result is a blank canvas.
[download.svg.zip](https://github.com/ImageOptim/ImageOptim/files/1890151/download.svg.zip)

**Comment by kornelski** [comment]
I can reproduce it with bare `svgcleaner` executable without ImageOptim, so I've reported that to the original author: https://github.com/RazrFalcon/svgcleaner/issues/139
