### ISSUE TITLE
Auto-updates broken for beta releases

### ISSUE THREAD

**Issue by core-code** [ImageOptim/ImageOptim#257]
1.8.0a1 still claims 'ImageOptim 1.8.0a1 is currently the newest version available.' although 1.8.0 final has been released.

the reason is CFBundleVersion is set to '1.8.0a1', which to Sparkle, is identical with '1.8.0'.
Sparkle really requires that the CFBundleVersion is set to a monotonically incrementing integer...

**Comment by kornelski** [comment]
Beta versions use separate appcasts, so they update only from beta to beta. The content is the same, so there's no need to update.

**Comment by core-code** [comment]
thats very weird. i don't know why a user would want to stay on unstable alpha until the next alpha is released ... but if thats you real intention then please feel free to close this. thanks.

**Comment by kornelski** [comment]
That's the intention. Otherwise all my beta testers would be gone after one release :)
