### ISSUE TITLE
ImageOptim doesn't work on macOS High Sierra

### ISSUE THREAD

**Issue by bodydouble** [ImageOptim/ImageOptim#264]
I don't know why but they doen't work at all. (ImageOptim 1.6.0 ~ 1.8.0)
![imageoptim 1 8 0](https://user-images.githubusercontent.com/42298400/43992680-ba9830ba-9dbc-11e8-9acd-5bb6d47f46c6.png)

It seems to work only under version 1.5.6
![imageoptim 1 5 6](https://user-images.githubusercontent.com/42298400/43992685-c2cdd398-9dbc-11e8-8145-f8cf3c9205d7.png)

-

macOS High Sierra 10.13.6(17G65)
Node.js 10.8.0 Current

MacBook Pro (Retina, Mid 2012)
2.3 GHz Intel Core i7
16GB 1600 MHz DDR3
NVIDIA GeForce GT 650M 1024 MB
Intel HD Graphics 4000 1536 MB

**Comment by kornelski** [comment]
It's been developed using High Sierra, so that's the best supported version of the system.

Hover mouse over the red icon, or use Console.app, to learn why it doesn't work. In 99% of cases that's because you're using a network drive or don't have permission to overwrite the file.

**Comment by bodydouble** [comment]
![2018-08-12 1 51 04 pm](https://user-images.githubusercontent.com/42298400/43998704-143c5de2-9e37-11e8-910c-878dd9ec315f.png)

I have captured an error message. Thanks for the answer!

**Comment by bodydouble** [comment]
![imageoptim error](https://user-images.githubusercontent.com/42298400/43998720-78062e48-9e37-11e8-9819-e0711639bfb2.png)

I have captured an error message. Thanks for the answer!

**Comment by bodydouble** [comment]
![imageoptim error](https://user-images.githubusercontent.com/42298400/43998748-1b5bfb5e-9e38-11e8-8fde-9eeb07242c39.png)

I have captured an error message. Thanks for the answer!

**Comment by kornelski** [comment]
It looks like `ImageOptim.app` is damaged. Delete it and download again.
