### ISSUE TITLE
Feature request: target file size for lossy resizing

### ISSUE THREAD

**Issue by HowBowers** [ImageOptim/ImageOptim#268]
I found this app yesterday and really appreciate what it does.

I work in advertising and often get a folder of banner ads from clients that need to be resized to 40K or under in order to get loaded into ad servers (typically, I have to make the target 38k as file systems end up adding kilobyte or two along the way).

I'd like to request an option when using lossy compression to hit a target file size instead of using the slider to select a particular quality setting.

Thank you again!

**Comment by kornelski** [comment]
That's a very nice use-case. Thanks for the suggestion.

I'm not sure *how* to add it, given my self-imposed absolute ban on adding any new buttons to the main window, ever (if I did "but only one" for every feature request I get, ImageOptim would look like Space Shuttle dashboard already).

**Comment by HowBowers** [comment]
Keeping off of the main window is imperative—the simplicity of the UI is
one of the program's strong points. I'd add it to the Quality tab in the
preferences, as an option under the quality sliders. I've placed a mock up
below (hopefully it works, I've never tried posting an image before).

[image: imageopt-ui.png]

**Comment by kornelski** [comment]
Unfortunately the image didn't survive.

**Comment by HowBowers** [comment]
![imageopt-ui](https://user-images.githubusercontent.com/6526177/45307936-4e14c400-b4ee-11e8-9869-86f21cb7f1be.png)
Maybe this time it will work.

**Comment by HowBowers** [comment]
Ah, there it is! The concept is when you enable the target file size, the sliders gray out. Unchecking it would make them active again.

**Comment by jonerikj** [comment]
In been looking for this for a long time! Any update on this?

**Comment by kornelski** [comment]
This will probably never happen. Target file size is not something that could be set as a global preference for all images, and ImageOptim UI doesn't have room for it anywhere else.

**Comment by jonerikj** [comment]
I do bulk compressing of JPGs to specific file size in terminal using JPEGOptim. I dont understand why it is so hard to include in ImageOptim as it already includes jpegoptim.

**Comment by kornelski** [comment]
It's not hard at all. It's just feature creep and unfocused UI design.
