### ISSUE TITLE
Crash when updating 1.8.1a3 to 1.8.1a4

### ISSUE THREAD

**Issue by chrismessina** [ImageOptim/ImageOptim#271]
When I go through the typical flow of updating the app, it crashes when it attempts to download the new version.

![cleanshot 2018-09-25 at 12 21 21](https://user-images.githubusercontent.com/22610/46037758-0aa98080-c0be-11e8-90ed-93c36cc05305.gif)

Perhaps it's an issue w/ Sparkle not having sufficient permissions (this is in macOS Mojave)?

`default	12:12:38.526426 -0700	ImageOptim	Sparkle: Authorization required to change permissions of file:///var/folders/00/0s6z0000h01000cxqpysvccm0034vw/T/TemporaryItems/(A%20Document%20Being%20Saved%20By%20ImageOptim)/permission_test to match file:///Applications/ImageOptim.app/
`

**Comment by kornelski** [comment]
Thanks. That's a bug in a3, and it's fixed in a4, but you'll need to upgrade manually.
