### ISSUE TITLE
WebP support

### ISSUE THREAD

**Issue by tsilcher** [ImageOptim/ImageOptim#278]
I just saw [another service](https://shrinkme.app/) offering [**WebP**](https://en.wikipedia.org/wiki/WebP) compression as well. Just wanted to suggest that you might consider adding this to the list of supported formats.

Thanks.

**Comment by kornelski** [comment]
But what would that do in ImageOptim?

WebP is a lossy format, and there are no optimizers for it. So given a WebP file I can only lower its quality further.

**Comment by tsilcher** [comment]
According to [Wikipedia](https://en.wikipedia.org/wiki/WebP) it allows both lossy and lossless compression.

**Comment by kornelski** [comment]
I mean if it's lossless, then you can't do anything with it at all. Recompressing lossless as lossless gives the exact same file back.

**Comment by b-b0t** [comment]
I know this is closed but just for those who really want this: https://webponize.org/

**Comment by alexlii1971** [comment]
How manny Browser support webpage now please?

**Comment by vitavalka** [comment]
I would like to see this in ImageOptim as well.

**Comment by dsuryadi** [comment]
https://developers.google.com/speed/webp

**Comment by kornelski** [comment]
That's still not actionable from a perspective of an optimizer. WebP still has no optimization tools, and as far as I know it doesn't even have an alternative implementation. And ImageOptim's UI model is not well-suited for conversions.

In terms of non-standard or not-yet-standard format, I'm planning to release tools for the AVIF format when it lands in browsers (there are plans for Firefox and a prototype for Chromium, so I'm hopeful it'll be soon-ish). 

AVIF is half size of WebP. It's a bigger leap over WebP, than WebP was over JPEG.

**Comment by sergiotapia** [comment]
With all due respect Kornel, webp kind of won now in 2025, is supported in mobile, and it would kick a lot of ass if there was a toggle in imageoptim where I can say "Convert to webp automatically!" 🙏 hopefully you reconsider!
