### ISSUE TITLE
Mac OS 10.14  crash

### ISSUE THREAD

**Issue by landerson85** [ImageOptim/ImageOptim#283]
Mac OS 10.14  crash

**Comment by kornelski** [comment]
Fixed https://imageoptim.com/changelog.html#v1.8.1b4

**Comment by landerson85** [comment]
1.8.5
Replaced old OptiPNG with OxiPNG — a fancy new parallel Rust rewrite
Experimental version of Sparkle updater testing new ed25519 signatures
Fixes for crashes especially frequent in macOS Mojave

No version of 1.8.1
But the latest version also has problems.
