### ISSUE TITLE
Mysterious 1.8.6 Version

### ISSUE THREAD

**Issue by FJdeKermadec** [ImageOptim/ImageOptim#286]
[ImageOptim’s appcast](https://imageoptim.com/appcast.xml) is currently pushing version 1.8.6, but ImageOptim itself cannot download the update, putting up an error instead.

It looks like the appcast file contains a syntax error, which interferes with the XML parsing: unless I am mistaken (and I could easily be), there is a missing `</sparkle:deltas>` tag before the last `</item>` tag.

Furthermore, the “Download for Free” button on the homepage [currently points to v. 1.8.5](https://imageoptim.com/ImageOptim.tbz2).

Is 1.8.6 ready for public release?

**Comment by kornelski** [comment]
That was supposed to be a fix that didn't actually do what it was supposed to :)

**Comment by aaronraimist** [comment]
Fixed by 1.8.7?

**Comment by kornelski** [comment]
Maybe :)
