### ISSUE TITLE
Where is the undo menu item?

### ISSUE THREAD

**Issue by highvoltaged** [ImageOptim/ImageOptim#287]
There used to be an undo option in the menu which i used constantly, cause it overwrites the files automatically. Now i have to duplicate my folders before trying to figure out the compression amount.

When working on Google anim banners , every single file size matters, and without undo this is a major workflow problem. 

Is there something i'm missing here?

**Comment by kornelski** [comment]
I haven't made any (intentional) changes to Undo recently.

Can provide more information/screenshots about what's missing?

**Comment by highvoltaged** [comment]
Thanks for the quick reply,
Here is my menu without added files: https://prnt.sc/m4cygc

As soon as i add files, the Undo turns into "Undo Add" which only undos the files being added https://prnt.sc/m4cyw7

**Comment by kornelski** [comment]
Hmm, I think it was always like this.  To undo changes of a file you need File -> Revert. I guess Undo would be a sensible place to actually undo file changes, but I never wired these up.

**Comment by highvoltaged** [comment]
Ok must have been a momentary lapse of reason by me, yeah i now see the revert in the file menu, and it alraeady has my custom shortcut..  sorry my bad
