### ISSUE TITLE
ImageOptim/Sparkle/bin/sign_update: No such file or directory

### ISSUE THREAD

**Issue by Spaino** [ImageOptim/ImageOptim#290]
build failed error:
Sparkle Test App
 /Users/UserName/SomeOnedirectory/ImageOptim/Sparkle/bin/sign_update: No such file or directory

sign_update is binary file, how is setting for Xcode?

**Comment by kornelski** [comment]
You're not building ImageOptim. Xcode has selected wrong scheme for you, and instead chose to build a useless demo application from one of the libraries that ImageOptim uses.

Delete Sparkle's schemes from your Xcode's scheme config.

**Comment by Tom01** [comment]
Can you fix that, please?
