### ISSUE TITLE
Add "Progressive JPEG Encoding" Option in Preferences

### ISSUE THREAD

**Issue by ylluminate** [ImageOptim/ImageOptim#299]
I have a situation where we need to optimize a lot of files (continually) and need progressive loading JPEGs even if they're not smaller. Can we please have an option to force one way or the other? A radio option list would probably work best for this:
```
Progressive JPEG Encoding:
(•) Use Best Size Result (ImageOptim has always done this by default!)
( ) Always Use Progressive Loading
( ) Never Use Progressive Loading
```

Already aware of this issue: https://github.com/ImageOptim/ImageOptim/issues/75 - we just need a way to force it one way or the other without always allowing the system to pick the smallest size.

**Comment by kornelski** [comment]
What's your use-case that needs progressive so absolutely?

Progressive is pretty much always better, except very small files (5-9KB), where it shouldn't matter for anyone whether it's progressive or not, because even on a dial-up modem these would load fast enough.

**Comment by ppamorim** [comment]
@kornelski I am using some JPEGs in a microcontroller and the decoder for progressive JPEG is too big (we are talking about little megabytes of storage) for the system. Knowing that the program is used to display images, it only works with baseline images.
