### ISSUE TITLE
Mac 10.15 Catalina opens gifs in textedit mode

### ISSUE THREAD

**Issue by yoonwluv** [ImageOptim/ImageOptim#302]
Mac Catalina 10.15 opens my gifs in textedit mode after converting them through imageoptim and I don't know how to fix this.

**Comment by kornelski** [comment]
I can't reproduce the problem on Catalina. 

I you do Get Info in Finder on that file, is it recognized as GIF? Have you have changed what app handles GIFs?

<img width="261" alt="Screenshot 2019-10-12 at 18 58 23" src="https://user-images.githubusercontent.com/72159/66705721-5909db80-ed22-11e9-9197-0fd002835125.png">

<img width="261" alt="Screenshot 2019-10-12 at 18 57 53" src="https://user-images.githubusercontent.com/72159/66705723-5c04cc00-ed22-11e9-9cee-d9773d929322.png">

**Comment by yoonwluv** [comment]
> I can't reproduce the problem on Catalina.
> 
> If you do Get Info in Finder on that file, is it recognized as GIF? Have you changed what app handles GIFs?
> 
> <img alt="Screenshot 2019-10-12 at 18 58 23" width="261" src="https://user-images.githubusercontent.com/72159/66705721-5909db80-ed22-11e9-9197-0fd002835125.png">
> 
> <img alt="Screenshot 2019-10-12 at 18 57 53" width="261" src="https://user-images.githubusercontent.com/72159/66705723-5c04cc00-ed22-11e9-9cee-d9773d929322.png">

No I haven't changed anything, after I updated from Mac OS Mojave to Catalina, I tried to use ImageOptim to lower the MB count on a gif but after converting it just saves as a TextEdit.
![ex1](https://user-images.githubusercontent.com/56467075/67067221-79330380-f143-11e9-98df-cc354bed6d9d.JPG)
![ex2](https://user-images.githubusercontent.com/56467075/67067225-7d5f2100-f143-11e9-86cc-467fdaccaf7c.JPG)

**Comment by kornelski** [comment]
Oh, you don't use filename extensions. Yeah, stripping Finder metadata will strip the Classic Mac OS information it uses about files in place of filename extensions.

I suggest naming the file `1.gif`

**Comment by yoonwluv** [comment]
Oh that worked, thank you!
