### ISSUE TITLE
Unnecessary spin-up of external hard drives

### ISSUE THREAD

**Issue by marcelashun** [ImageOptim/ImageOptim#303]
On launch ImageOptim wakes up every external hard drive of my system one at a time, independently of necessity. During spinup MacOs is somewhat unresponsive. Maybe there is potential for improvement there.

**Comment by kornelski** [comment]
That's very surprising, because ImageOptim doesn't try to scan disks or anything like that. I'm not sure where is that coming from.

**Comment by marcelashun** [comment]
I see, maybe it's system specific then or not an issue of ImageOptim after all, I can't tell. I use ImageOptim since macOS Mojave and now Catalina on an iMac 27" late 2012. I have two Seagate external hard drives connected to it. In energy settings "Put hard disks to sleep when possible" is active.
