### ISSUE TITLE
no matches found: *.png

### ISSUE THREAD

**Issue by spencerclrk** [ImageOptim/ImageOptim#308]
Trying to run `/Applications/ImageOptim.app/Contents/MacOS/ImageOptim *.png` on a set of images but keep getting `no matches found: *.png`

Am I running this code incorrectly? Is it looking in the Applications directory instead?

ImageOptim 1.8.8 on macOS 10.15.2

**Comment by kornelski** [comment]
`no matches found: *.png` means the current directory does not contain any files with `*.png` extension. You have to `cd` to the correct directory first.

**Comment by spencerclrk** [comment]
Terminal did not have full disk access. Typical issues with new Mac OS versions.
