### ISSUE TITLE
Cannot save files on MacOS Catalina 10.15.2

### ISSUE THREAD

**Issue by 13milliseconds** [ImageOptim/ImageOptim#311]
The problem has appeared since updating MacOS to Catalina. Files are saved as hidden files (".filename~imageoptim.jpg") but never saved over the original file. 

ImageOptim was give both "Full Disk access" and "Developer Tools" but no change in behavior.

**Comment by kornelski** [comment]
Search for ImageOptim in Console.app. It should explain more what happened.

**Comment by 13milliseconds** [comment]
Thanks for the pointer. The error is created by the fact that the file cannot be sent to trash before being replaced with the optimized version.

`Can't trash /Users/username/Downloads/filename.png Error Domain=NSCocoaErrorDomain Code=512 "“filename (1).png” couldn’t be moved to “.Trash”." UserInfo={NSSourceFilePathErrorKey=/Users/username/Downloads/filename.png, NSUserStringVariant=(
    Move
), NSDestinationFilePath=/Users/username/.Trash/filename.png, NSFilePath=/Users/username/Downloads/filename.png, NSUnderlyingError=0x600002f8ad30 {Error Domain=NSPOSIXErrorDomain Code=20 "Not a directory"}}`

This is a problem I've been having since updating to Catalina and did not realize was affecting ImageOption as well.  I'll close this since it is not an ImageOptim problem.
