### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by 9mm** [ImageOptim/ImageOptim#312]
I use ImageOptim almost every day, it seems like these issues are stacking up. I notice some weird quirks which I'm OK with, but am wondering is there a project everyone is using instead now? Is this project dead?

**Comment by kornelski** [comment]
ImageOptim works fine IMHO, so I don't feel the need to release updates just for appearance.

I should probably be more aggressive about closing issues. I'm intending to keep the UI minimal (the project is 13 years old and the app is not bloated yet!), so my answer to most feature request is "no" :)
