### ISSUE TITLE
Convert .HEIC in JPG / PNG files

### ISSUE THREAD

**Issue by fcatapano** [ImageOptim/ImageOptim#332]
Hey, not really a bug but more a feature request. It would be nice if it could convert oSX native format: .HEIC into something a bit more usable such as JPG and PNGs

**Comment by kornelski** [comment]
Unfortunately HEIC uses a patented H.265 codec, so it's radioactive from legal/licensing perspective. I'm not touching it.

**Comment by sindresorhus** [comment]
I have a free app for this: https://apps.apple.com/app/id1294126402
