### ISSUE TITLE
Option to convert to sRGB

### ISSUE THREAD

**Issue by coffeeandpixels** [ImageOptim/ImageOptim#360]
Hi. I’m not sure if what I’m asking is as simple as it sounds, but is it possible you could please add a setting to convert images to sRGB during optimisation? I don’t know of any software that can batch convert colour spaces.

**Comment by kornelski** [comment]
If you enable the Lossy option, it will be done by the tools that recompress the image.

Color profile conversion is not a lossless operation, so that's why the lossless mode doesn't do it. Perhaps there should be an almost-lossless mode.

**Comment by coffeeandpixels** [comment]
Oh that is awesome!! Thank you for your quick response, too.

I spent the day resizing and optimising images from a client’s product catalogue. When I had nearly finished, I realised most of the source images were CMYK. After your reply, I checked the output. ImageOptim had indeed converted them all to sRGB. 😅

Thanks so much for this software!!!
