### ISSUE TITLE
Macbook battery drains when power source is plugged in

### ISSUE THREAD

**Issue by CorianderTree** [ImageOptim/ImageOptim#395]
Model Name:	MacBook Pro
  Model Identifier:	MacBookPro14,3
  Processor Name:	Intel Core i7
  Processor Speed:	3.1 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
  Boot ROM Version:	447.40.12.0.0
  SMC Version (system):	2.45f5

OS: Mojave version 10.14.6 (18G8022)
Model: MacBook Pro (15-inch, 2017)

This issue occurs in: ImageOptim Beta build 1.8.9a1 and Version 1.8.8.

When my Macbook is plugged in, the computer stops charging the battery and the battery starts to drain. 
Under battery it says "Battery Not Charging" and Power Source: Power Adapter.
The app is the cause.
I know it's the case as if I close the app the computer starts charging the battery again properly. 
The battery issue only occurs when the app is processing files. 
So when you start the app the battery is still charging normally. 
But, after you start processing a bulk amount images the issue occurs.

I've tried disabling different things (e.g. turning off Jpegtran or lossy minification) and the issue occurs no matter.

**Comment by kornelski** [comment]
High energy usage is expected when the CPU is fully utilized. This Intel CPU is rated at 65W, but in good conditions Intel CPUs can draw much more, and that's not counting energy usage of the rest of the computer. If you don't have a strong-enough power supply, that can draw more power than it provides, and drain the battery too.
