### ISSUE TITLE
Animated PNG compression

### ISSUE THREAD

**Issue by derpycoder** [ImageOptim/ImageOptim#398]
Hey guys,

This tool is a life saver, I love it. I am using it to compress all the files in my personal projects.

However, when I try to compress APNG file, the compressor compresses only the first frame.

I'm trying to compress the fluent emoji icons!

[Official Repo](https://github.com/microsoft/fluentui-emoji)
[Animated PNGs Repo](https://github.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis)

Currently I'm using [TinyPng](https://tinypng.com/), to manually compress animated png.

At first I raised an issue on Imageoptim CLI Git repo. I was asked to post here. See:
https://github.com/JamieMason/ImageOptim-CLI/issues/195#issue-1422872407

Perhaps, the default behaviour when compressing animated images should be to preserve the animation, and maybe a flag can be introduce to remove the animation. (Something like cull or decimate or Thanos snap animations 😅)

**Comment by kornelski** [comment]
I don't plan to. I think Animated PNG is obsolete, and an evolutionary dead-end. I don't think anybody should be using it.

In 24-bit mode it has worse compression than GIF. In 8-bit mode it has worse quality than GIF. In all cases the compression is order of magnitude worse than any modern video format. Even if you need something to work in `<img>` in Chrome (which refuses to add support for MP4 in `<img>`), animated WebP now works in all major browsers, and there's animated AVIF too.
