### ISSUE TITLE
“ImageOptim” is damaged and can’t be opened. You should move it to the Trash.

### ISSUE THREAD

**Issue by javothemes** [ImageOptim/ImageOptim#401]
<img width="427" alt="image" src="https://user-images.githubusercontent.com/28474304/210131638-5cc4b673-fcec-4e3c-a906-be9c634b4d34.png">

I just downloaded from your site and unzipped. 
But it's not working with the error.

Using M1 and the newest version of IOS.

Thank you,

**Comment by kornelski** [comment]
Sorry, I can't fix this issue. It's caused by Apple's Code Signing, and it outside of my control.
