### ISSUE TITLE
Well it caused my PC to fully freeze and crash due to the errors.

### ISSUE THREAD

**Issue by vipexv** [ImageOptim/ImageOptim#409]
So i didn't write the correct name for they optimizer application, and it literalally decided to go through all of the 400+ imgaes while spamming the same error which ended up crashing my PC, not sure why they wouldn't make it stop the whole process on the first imgae but up to them.

**Comment by NiklasBr** [comment]
Are you sure this is the correct place to report your issue? ImageOptim is a Mac-only application.

**Comment by vipexv** [comment]
I installed it through VS Code, to be quite fair i have not used an image optimizer before, i usually use a Texture Optimizer for other things, but had an inventory that had Large Icons for some reason, is it Mac only even in VS Code?

**Comment by NiklasBr** [comment]
This app has nothing to do with VS Code, it is a self-contained app and not an extension.

**Comment by vipexv** [comment]
Just checked it, and yes it's the wrong github, there's another one specifically made for VS Code, so sorry!

This is what i was referring to.
"https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-optimize-images"
