### ISSUE TITLE
Replicate ImageOptim exact optimizations

### ISSUE THREAD

**Issue by taosx** [ImageOptim/ImageOptim#418]
I'm trying to write a backup+optimize and restore tool with ImageOptim as the standard for compressed jpeg's. However I have encountered an issue where the files generated by my tool using [MozJPEG](https://github.com/ImageOptim/mozjpeg-rust) turn out to be different in term of sizes compared to the ones generated by [ImageOptim](https://github.com/ImageOptim/ImageOptim). That was a bit surprising as I thought MozJPEG was used by ImageOptim as well.

Steps taken so far:
- **Stripping Metadata**: Removed metadata from both my tool and ImageOptim generated images.
- **Adjusting Quality**: I experimented with different quality settings in case there's a mismatch between ImageOptim and MozJPEG
- **Using jpegtrans**: Applied jpegtrans on top of MozJPEG (files turn even smaller with no visible artifacts at high zoom) but still different in size.
- **Isolating ImageOptim's Features**: Disabling everything in ImageOptim except JPEGOptim.
- **Modified MozJPEG's settings**: I've tried many permutations of MozJPEG's settings in my tool.

Nothing worked. So my question is, is there some trick that the app uses that's only specific to ImageOptim? I'll link relevant code after I get back.

Edit:
- [Code Example](https://github.com/taosx/optimize-example/blob/main/src/optimize.rs)
- I've found an [older similar issue](https://github.com/ImageOptim/ImageOptim/issues/251) where kornelski mentioned about MozJPEG used alongside jpegoptim so I'll give that a try.
- Found [another one](https://github.com/ImageOptim/ImageOptim/issues/102)

_I apologize as this is not exactly an issue for ImageOptim and I understand if it's closed._

**Comment by kornelski** [comment]
In case of MozJPEG you will probably find tiny differences from ImageOptim using Apple's image frameworks to load JPEGs, rather than libjpeg itself. This adds processing of color profiles.

**Comment by taosx** [comment]
I'm still struggling with matching the exact output or the results for all formats that ImageOptim provides. In that view I've decided to go with the simplest solution for now in order to release it and then take a deeper dive into image processing and compression. I'll also follow up on apple's image framework. Thank you!
