### ISSUE TITLE
Photos lost after compression completes

### ISSUE THREAD

**Issue by jamesjaxx** [ImageOptim/ImageOptim#421]
Whenever I run ImageOptim, once the run successfully completes the optimised files are deleted from the target folder. There doesn't seem to be a pattern to which files are kept / deleted. 

I have tried all the usual troubleshooting steps: removed and reinstalled ImageOptim, checked permissions and priveleges and cannot see anything that would cause the issue. 

It's making it impossible to use ImageOptim now and I've been a long standing user. Not sure if anyone else is experiencing the same issue? 

Imageoptim build: 1.8.8
macOS: 13.0.1

**Comment by woefi** [comment]
First, your OS version looks suspiciously outdated, macOS 13 is now at 13.5.2 so maybe it is a result of a "point zero release bug"
Second, maybe it has something to do with the underlying filesystem, have you tried optimizing images stored on another volume/disk with a known _different_ filesystem? Maybe testing with an USB-key formatted to APFS, HFS+ or exFAT might change anything?

**Comment by BlackSheep42** [comment]
I have exactly the same issue and it's totally random. If I rename say eight files in one go one, two or maybe three will vanish from the folder containing the original files. The files are not being deleted, they are actually being renamed with a full stop in-front of the original file name which causes them to disappear from the standard MacOS system view. Currently to get around this issue, I open the files to be compressed in Preview prior to using ImageOptim, then if any files are renamed I remove the newly added full stop from their amended title and they reappear in the folder.

**Comment by gilzis** [comment]
Are you optimizing directly on Dropbox/Google drive by any chance? It start noticing perhaps this is the issue

**Comment by BlackSheep42** [comment]
Yes I am. This issue does seem to have started after the major update to Dropbox which now uses Apple's updated File Provider API. Not one hundred percent sure, but I don't think I've had the issue when files have been compressed locally. I'll start to do that from now on to see if the issue stops.

**Comment by gingerbeardman** [comment]
I think the files are changed by ImahgeOptim so quickly (created, deleted, renamed) that Dropbox loses track.

**Comment by kornelski** [comment]
Any suggestions how to detect Dropbox's folders? Do they have a hidden `.dropbox` dir?
