### ISSUE TITLE
1.9.2 Right clic problem

### ISSUE THREAD

**Issue by madjuju** [ImageOptim/ImageOptim#424]
in the finder
right clic on a file then "imageoptimize" it's open the app but no file is loaded, no file optimized$

Drag & Drop is ok

**Comment by gingerbeardman** [comment]
Right click works for me with 1.9.2


https://github.com/ImageOptim/ImageOptim/assets/49612/0101cd4a-4f33-494b-ab29-b33f2e852550

**Comment by madjuju** [comment]
https://github.com/ImageOptim/ImageOptim/assets/5285199/c7b52e60-3ca9-4182-966e-ddc6d98da443

**Comment by madjuju** [comment]
https://github.com/ImageOptim/ImageOptim/assets/5285199/8de0954c-aa4a-4c12-b926-f24178865807

**Comment by madjuju** [comment]
https://github.com/ImageOptim/ImageOptim/assets/5285199/28ee0752-6554-4071-b982-49b805cccc1d

**Comment by gingerbeardman** [comment]
> Enregistrement.de.l.ecran.2023-10-18.a.19.08.49-1

Where does the ImageOptim menu item that is not "open with" come from? is it an action/service/workflow?

**Comment by phripley** [comment]
> 
> Where does the "ImageOptimize" menu item that is not "open with" come from? is it an action/service/workflow?
> 

I have it as well.  It is an extension.  See screenshot.

<img width="715" alt="Screenshot 2023-10-18 at 2 55 41 PM" src="https://github.com/ImageOptim/ImageOptim/assets/1319850/7ec29932-674a-4b91-a540-d6b2e83f19be">

I don't recall when it was installed.  Definitely before today's 1.9.2 update.

**Comment by kornelski** [comment]
This should be fixed. Make sure you don't have previous version somewhere (check for updates in the failing window).

**Comment by madjuju** [comment]
still broken
