### ISSUE TITLE
Too much window transparency

### ISSUE THREAD

**Issue by mrleblanc101** [ImageOptim/ImageOptim#426]
Maybe I'm nitpicking, but the background transparency changed and it's a bit disturbing.
![Screenshot 2023-10-18 at 1 17 05 PM](https://github.com/ImageOptim/ImageOptim/assets/17392251/a59d475d-725a-4f2e-b497-d1543a19706c)

**Comment by kornelski** [comment]
It should be opaque when there are any files in the window.

How did you get the application in a state that it shows the list, but without any files?

**Comment by mrleblanc101** [comment]
I opened the app 😂
It open like this by default every time for me.
I'm on Sonoma

**Comment by mrleblanc101** [comment]
Oh I should be seeing this ?
![DropArea](https://github.com/ImageOptim/ImageOptim/assets/17392251/62f91277-97ab-4da8-a65d-931c6cfabee6)
Well, I don't.
There seem to be a problem but it's very minor.

**Comment by woefi** [comment]
I now tried this on my Ventura installation.
I can reproduce this when I switch to **dark mode**. (It's just the big drop-icon what is missing)

As soon as I switch back to my (normally used) light mode the drop-icon is back again.

**Comment by woefi** [comment]
![Bildschirmfoto 2023-10-20 um 15 39 41](https://github.com/ImageOptim/ImageOptim/assets/70533823/83ddcd44-05ca-494d-89d7-76bcb3cb3eb9)
![Bildschirmfoto 2023-10-20 um 15 39 27](https://github.com/ImageOptim/ImageOptim/assets/70533823/6036e441-e25a-419e-a98e-87f49f133ce7)

**Comment by kornelski** [comment]
I've noticed that inheriting from `NSVisualEffectView` was causing such random issues. I've added the effect view as an extra virgin standalone unmodified view, and that seems to help.

Also, highly recommended:

![reduce transparency](https://github.com/ImageOptim/ImageOptim/assets/72159/9574b81e-ace2-4805-866c-a67d91e2b210)
