### ISSUE TITLE
Should Guetzli and JPEGtran be added to the About ImageOptim screen?

### ISSUE THREAD

**Issue by phripley** [ImageOptim/ImageOptim#428]
The About screen for ImageOptim 1.9.2 lists a number of 3rd party utilities.  For the most part these match the list in `Settings > Enable`, however both Guetzli and JPEGtran appear in the settings list but are absent in the About screen.  Perhaps they should be added?

![Screenshot 2023-10-19 at 12 55 57 PM](https://github.com/ImageOptim/ImageOptim/assets/1319850/cf19160b-b1d2-4731-abc0-e74511dde917)

**Comment by kornelski** [comment]
I've added guezli. jpegtran is from mozjpeg.
