### ISSUE TITLE
Can I ignore already compressed?

### ISSUE THREAD

**Issue by dfdgsdfg** [ImageOptim/ImageOptim#431]
In app development, image assets should be compressed . Also image assets are often added or deleted. At this time, I have to check which one is compressed or not.

Can I have this on this version?

By the way, thanks for your great work!

**Comment by kornelski** [comment]
ImageOptim keeps an SQLite database with hashes of files it couldn't optimize any more. So you can run it over the same set of files over and over again and it will learn to quickly skip maximally optimized files.
