### ISSUE TITLE
Images disappearing after compression while resident in Dropbox after update

### ISSUE THREAD

**Issue by BlackSheep42** [ImageOptim/ImageOptim#432]
If I optimise several files in one go one, two or maybe three will vanish from the folder containing the original files after the optimisation has finished. The files are not being deleted, they are actually being renamed with a full stop "."  in front of the original file name which causes them to disappear from the standard MacOS system view. If you press press Command + Shift + . you can view them.

This only seems to occur when files are optimised while resident in the latest version of Dropbox (compliant with Apple's updated File Provider API) and not locally on my Mac. In the older version I had no such issue.

I have reported this to Dropbox as well but I'm still waiting for a reply. I've also commented on this in another post reporting a similar problem https://github.com/ImageOptim/ImageOptim/issues/421 but it has been closed without any resolution.

I am running MacOS Ventura 13.6 and ImageOptim 1.8.8

**Comment by kornelski** [comment]
Did the beta build solve the issue for you?

**Comment by BlackSheep42** [comment]
I've just download the Beta. Will give it a try and let you know. Thanks.

**Comment by BlackSheep42** [comment]
So far, zero errors with the Beta!

**Comment by kornelski** [comment]
Dropbox is detected by either presence of /Dropbox/ in the path, or .dropbox hidden file. I suspect that subfoders in Dropbox folders that were renamed to something else may not be getting the workaround, so be careful about these. 

Anyway, it's kinda scary that a tool for storing files can just lose files when they're renamed and replaced quickly enough.
