### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by deepj** [ImageOptim/ImageOptim#5]

**Comment by kevinSuttle** [comment]
Is there a way to compress SVGs with the ImageOptim UI? Hard to get non-coders to open a terminal...

**Comment by bdarfler** [comment]
@kevinSuttle why do they need to `make` it? There are installers for mac and windows and I assume non coders are not on linux.

**Comment by hungdm9999** [comment]
IM seems does not support SVG right now, only raster image (i.e: PNG, JPG) supported.

**Comment by basiclines** [comment]
+1

**Comment by hungdm9999** [comment]
Pdf is also vector file format and there is some commercial shrinker on the
market.
You may convert to PDF and try?

**Comment by sindresorhus** [comment]
https://jakearchibald.github.io/svgomg/ is a Web UI for SVGO, so it definitely can be browserified.

**Comment by voxpelli** [comment]
To get the same functionality as the svgomg web-tool into ImageOptim would be very nice – many of the images nowadays are SVG:s so to be able to just drag all – raster and vector images – into the same tool to get them optimized would be very nice – a single flow for it all.

**Comment by pornel** [comment]
Some progress on this: I've managed to make a minimal standalone build of SVGO (so it's 1/10th of what node_modules takes)

**Comment by skunkworker** [comment]
Any additional update on this?

**Comment by jantimon** [comment]
SVGO 
https://www.npmjs.com/package/svgo

> 1,641,688 downloads in the last month

It supports loseless conversion and runs on node and as mentioned by @kevinSuttle in the browser.

How can I support you to finally close a 3 year old issue?

**Comment by pornel** [comment]
1. Get ImageOptim compiling (if you're getting build errors let me know - usually happens when dependencies on sourceforge.net are moved/deleted)

2. Add a Worker class using one of existing subclasses as a template

3. In `fileType:` add SVG detection

4. In `doEnqueueWorkersInCPUQueue` add your worker

**Comment by pornel** [comment]
It also needs some GUI work to have checkbox in preferences + detection if nodejs present on the system.

**Comment by victorwestmann** [comment]
+1!

**Comment by pornel** [comment]
Added in 1.7.0a2

https://imageoptim.com/changelog.html

**Comment by Saklad5** [comment]
Shouldn’t this be closed?
