### ISSUE TITLE
Unauthorized ImageOptim on Mac App Store for $9.99?

### ISSUE THREAD

**Issue by dataxpress** [ImageOptim/ImageOptim#56]
Noticed that ImageOptim is on the Mac App Store for $9.99. 

I'm not terribly familiar with open source licensing, but I'm almost certain that this is not allowed.

Should I (or somebody) contact the App Store support about this? 

https://itunes.apple.com/us/app/imageoptim/id849284574?mt=12

**Comment by christopheranderton** [comment]
Cheers (sorry for posting in a closed thread). This one seems very much as a candidate: http://forums.macrumors.com/showthread.php?t=1859723

**Comment by mathiasbynens** [comment]
> http://forums.macrumors.com/showthread.php?t=1859723

http://forums.macrumors.com/showthread.php?t=1859723#post20896473 is pretty funny:

> Oops! Got my library names mixed up earlier. Lossless compression is powered by the OptiPNG library, not ImageOptim. Sorry for any confusion.

Oops indeed.

**Comment by pornel** [comment]
I think littlePNG is in the clear. It's using pngquant and optipng, which are on permissive licenses allowing DRM and other shenanigans of the AppStore.

Its UI is a bit similar to ImageOptim, but that's fine. I'm not claiming to have exclusivity on a window with an arrow and a button :)

**Comment by christopheranderton** [comment]
A new candidate. https://itunes.apple.com/app/file-optimizer/id1034693452?mt=12 Uses plenty of GPLv2 stuff, and i think some parts from ImageOptim (the libimageoptimjpeg.dylib looks suspicious). May not be related to ImageOptim directly however. Don't know if you can see anything on the screenshot (i used Hopper Disassembler with libimageoptimjpeg.dylib):

![screenshot 2016-03-21 at 16 15 45](https://cloud.githubusercontent.com/assets/1305802/13923312/63357702-ef80-11e5-9164-c737cce5bd80.png)
![screenshot 2016-03-21 at 16 17 34](https://cloud.githubusercontent.com/assets/1305802/13923343/830549ae-ef80-11e5-9a30-546a52160a9e.png)

**Comment by pornel** [comment]
File Optimizer is a clear violation. It has `ImageOptimController` class, same preference names, same localised strings files, contains GPL gifsicle, and has original credits and copyright notices removed.

I've notified Apple about it.
