### ISSUE TITLE
Printing ImageOptim images as PDF in Safari

### ISSUE THREAD

**Issue by rosenvinge** [ImageOptim/ImageOptim#66]
I have used ImageOptim to optimize images for a website I'm working on. The images look great except when I try to "print" them as PDFs in Safari.

Here is a sample image as it appears in browsers:
![orchestra](https://cloud.githubusercontent.com/assets/8620534/4112579/1b81ca96-3230-11e4-9c8e-b8fad5d6fbb2.jpg)
And here it is as it appears in a PDF "printed" from Safari:
![orchestra-imageoptim](https://cloud.githubusercontent.com/assets/8620534/4112581/370c2522-3230-11e4-9186-5ecd5a556ac8.jpg)

This problem occurs in Safari (and also in iCab), but not in Firefox, Opera, or Chrome (all on Mac).
Any suggestions for making the image behave in Safari?
Thanks!

**Comment by fulldecent** [comment]
Can you please attach a sample image. Also, is a RADAR filed for this issue with Safari?
