### ISSUE TITLE
Progressive JPEGs

### ISSUE THREAD

**Issue by toncid** [ImageOptim/ImageOptim#75]
Hello,

Great tool you have here! :+1: 

Is it possible to add the "progressive" flag for JPEG transcoders? We feel that large hero banners on a website should be progressive and thus provide some visual feedback to the visitor while they're loading.

Thoughts?

**Comment by Voodoopupp** [comment]
Hi there,

is it possible the other way around? What if you do not want progressive images? Would be great to have an option to avoid interlacing!

**Comment by Voodoopupp** [comment]
Have a look at this: http://www.webperformancetoday.com/2014/09/17/progressive-image-rendering-good-evil/

True? Or better to go for progressive in web now? (a few years ago, it was said, that progressive is dead!?)

**Comment by pornel** [comment]
Please disregard the Radware "study". It's not a proper scientific study, but a marketing material using pseudoscience to get page views.

**Comment by Voodoopupp** [comment]
Okay, understand that. But what about avoiding progressive images? Any possibility for that?

**Comment by pornel** [comment]
ImageOptim will choose progressive or non-progressive based on which is smaller. There's no option to force either one manually.

Note that this Yahoo research predates MozJPEG, which has even better optimizations for progressive JPEG.

**Comment by nickspiel** [comment]
It would be great if we could specify which it uses. I feel so dirty if I don't get that green 'A' rating on webpagetest.org for compress images.

**Comment by pornel** [comment]
AFAIK webpagetest.org compares to file size at quality=75

**Comment by nickspiel** [comment]
They also require progressive images.

**Comment by pornel** [comment]
Have you got an example image that is better as non-progressive, but webpagetest flags as unoptimized?

**Comment by nickspiel** [comment]
Odd. I just resaved the images as progressive and ran them through ImageOptim again, all held the progressive optimisation. I have been getting these assets from my designer who assures me he did the same. 

I think the issue may be with my designer telling fibs.

I will keep an eye on it and let yo know If I come across it again.

**Comment by adamreisnz** [comment]
So there is no way to disable progressive JPEG's with a flag if you don't want your hero header image to start out as a black and white low res image...?

**Comment by kornelski** [comment]
I'm working on a fix for that.

**Comment by adamreisnz** [comment]
Awesome, thanks

**Comment by varadgunjal** [comment]
Just wanted to clairfy: you're saying that progressive JPEGs are generated by default right?

Great tool you have here, thanks!

**Comment by kornelski** [comment]
Progressive files are generated by default, with rare exception of (typically small, like <5kb) files that happen to compress better as baseline.

**Comment by ylluminate** [comment]
I have a situation where we need to optimize a lot of files (continually) and need progressive loading JPEGs even if they're not smaller. Can we please have an option to force one way or the other? A radio option list would probably work best for this:
```
Progressive JPEG Encoding:
(•) Use Best Size Result (ImageOptim has always done this by default!)
( ) Always Use Progressive Loading
( ) Never Use Progressive Loading
```
