### ISSUE TITLE
Photos lost while compressing :/

### ISSUE THREAD

**Issue by oliviacyy** [ImageOptim/ImageOptim#83]
Some of my photos were lost after i dragged them into the application imageoptim. Might be because my SD card which the photos were on, was quite full already. I wasn't able to find the missing photos on my whole mac. Urgent help needed. Thanks

**Comment by pornel** [comment]
Images should be in the trash or in the worst case as a hidden file (name 
starts with a dot)

**Comment by oliviacyy** [comment]
Thank you for replying. I can't find the lost images in the trash either. Is there a fastest way i can find them, if they are in a hidden file?

**Comment by pornel** [comment]
There's a hidden setting that enables showing of hidden files in the Finder 
http://www.macworld.co.uk/how-to/mac-software/how-show-hidden-files-in-mac-os-x-finder-3520878/

**Comment by fulldecent** [comment]
@oliviacyy  Can we close this issue?
